namespace ClassicChineseLanguagePack
{
    internal static class GrimoraCardCatalog
    {
        internal static readonly (string English, string Simplified, string Classical)[] All =
        {
            ("Skeleton", "骷髅", "枯骨"),
            ("Animator", "操偶师", "操傀者"),
            ("Apparition", "幽灵鬼影", "幽影"),
            ("Graven Ashes", "刻墓之烬", "刻冢烬"),
            ("Bal-Bal", "墓穴食尸鬼", "食尸冢鬼"),
            ("Banshee", "女妖", "女妖"),
            ("The Bartender", "酒保", "酒人"),
            ("Big Bones", "巨骨", "巨骨"),
            ("Burly Bones", "壮骨", "壮骨"),
            ("Beefy Bones", "蛮骨", "蛮骨"),
            ("Cal C. Um", "钙先生", "钙公"),
            ("Sizeable Bones", "硕骨", "硕骨"),
            ("Considerable Bones", "庞骨", "庞骨"),
            ("Vigorous Bones", "劲骨", "劲骨"),
            ("Hefty Bones", "重骨", "重骨"),
            ("Bloody Sack", "血渍麻袋", "血渍囊"),
            ("Bone Collective", "骸骨集群", "聚骨"),
            ("Bonehound", "寻骨猎犬", "寻骨犬"),
            ("The Bonelord", "骨王", "骨王"),
            ("Bonelord's Horn", "骨王的号角", "骨王之号"),
            ("Bone Heap", "骨堆", "积骨"),
            ("Bone Prince", "骨王子", "骨王子"),
            ("Boo Hag", "阴灵女巫", "鬼妪"),
            ("Calavera Catrina", "骷髅夫人", "髑髅夫人"),
            ("Catacomb", "墓穴军团", "冢众"),
            ("Centurion", "百夫长", "百夫长"),
            ("Compound Fracture", "混魂碎骨", "裂骨"),
            ("Dalgyal", "魔蛋", "魔卵"),
            ("Danse Macabre", "亡灵舞者", "死舞"),
            ("Deadeye", "死人眼", "死目"),
            ("Dead Hand", "死人手", "死手"),
            ("Dead Man Walking", "行尸走肉", "行尸走肉"),
            ("Pharaoh's Pets", "法老之宠", "法老之宠"),
            ("Death Knell", "鸣钟亡灵", "丧钟"),
            ("Chime", "铃铛", "铃"),
            ("Doll", "人偶", "偶人"),
            ("Draugr", "尸鬼", "尸鬼"),
            ("Drowned Soul", "淹死鬼", "溺魂"),
            ("Dybbuk", "附鬼", "附鬼"),
            ("Ectoplasm", "灵质", "灵质"),
            ("Boneclaw", "骨爪", "骨爪"),
            ("Boneless", "无骨者", "无骨"),
            ("Lesser Mummy", "次级木乃伊", "次木乃伊"),
            ("Eidolon", "英灵", "英灵"),
            ("Ember Spirit", "烬魂", "烬魂"),
            ("The Walkers", "行师走人", "行尸"),
            ("Festering Wretch", "溃烂行尸", "腐尸"),
            ("Flames", "火焰", "焰"),
            ("Flameskull", "烈焰颅骨", "焰颅"),
            ("Forgotten Man", "遗忘者", "遗人"),
            ("Frank & Stein", "弗兰肯和斯坦", "弗兰克与斯坦"),
            ("FrankenStein", "弗兰肯斯坦", "弗兰肯斯坦"),
            ("Fylgja", "陪伴者", "伴灵"),
            ("Warding Presence", "警戒之影", "卫影"),
            ("Mass Grave", "万人冢", "万人冢"),
            ("Rising Hunger", "暴食", "长饥"),
            ("Gashadokuro", "饿者骷髅", "饥骨"),
            ("Ghost Ship", "幽灵船", "鬼舟"),
            ("Giant", "巨人", "巨人"),
            ("Grateful Dead", "感恩亡魂", "感德亡魂"),
            ("Gravebard", "墓吟者", "墓吟者"),
            ("Grave Carver", "刻墓人", "刻冢者"),
            ("Gravedigger", "掘墓人", "掘冢者"),
            ("Sporedigger", "掘孢人", "掘蕈者"),
            ("Haltia", "哈尔蒂亚", "哈尔蒂亚"),
            ("Haunted Mirror", "闹鬼魔镜", "祟镜"),
            ("Headless Horseman", "无头骑士", "无首骑者"),
            ("Hellhand", "地狱魔爪", "狱爪"),
            ("Hell Hound", "地狱犬", "狱犬"),
            ("Hydra", "九头蛇", "九首蛇"),
            ("Jikininki", "食人鬼", "食人鬼"),
            ("Avalanche", "雪崩", "雪崩"),
            ("Glacier", "冰川", "冰川"),
            ("Frost Giant", "冰霜巨人", "霜巨人"),
            ("Ice Cube", "冰块", "冰块"),
            ("La Llorona", "哭泣女妖", "泣女妖"),
            ("Manananggal", "魔娜娜迦", "魔娜娜迦"),
            ("Moroi", "魔洛伊", "魔洛伊"),
            ("Mummy Lord", "木乃伊之王", "木乃伊王"),
            ("Necromancer", "死灵法师", "死灵巫"),
            ("Nixie", "水妖", "水妖"),
            ("Nosferat", "诺斯费拉图", "诺斯费拉图"),
            ("Ancient Obol", "古银币", "古奥波勒"),
            ("One Armed Bandit", "独臂强盗", "独臂盗"),
            ("Ourobones", "衔骨蛇", "衔骨蛇"),
            ("Plague Doctor", "疫医", "疫医"),
            ("Poltergeist", "恶灵", "恶灵"),
            ("Possessed Armour", "附魔铠甲", "附魂甲"),
            ("Project", "实验体", "试物"),
            ("Random Cards", "无形造物", "无形牌"),
            ("Revenant", "复生亡灵", "逆生魂"),
            ("Ripper", "开膛手", "剖者"),
            ("Rotten", "腐尸", "腐尸"),
            ("Twitching Arm", "抽搐的手臂", "搐臂"),
            ("Davy Jones Locker", "戴维·琼斯的储物柜", "戴维·琼斯之柜"),
            ("Yellowbeard", "黄胡子", "黄须"),
            ("Bluebeard", "蓝胡子", "蓝须"),
            ("Crossbones", "十字骨", "十字骨"),
            ("Davy Jones", "戴维·琼斯", "戴维·琼斯"),
            ("Exploding Pirate", "自爆海盗", "爆裂海盗"),
            ("First Mate Snag", "大副斯纳格", "大副斯纳格"),
            ("Polly", "波利", "波利"),
            ("Privateer", "私掠船长", "私掠者"),
            ("Swashbuckler", "豪侠", "豪侠"),
            ("Sarcophagus", "石棺", "石椁"),
            ("Screaming Skull", "尖叫颅骨", "啸颅"),
            ("Silbon", "希尔邦", "希尔邦"),
            ("Skelemagus", "骷髅法师", "枯骨巫"),
            ("Skeleton Army", "骷髅军团", "枯骨军"),
            ("Slinger's Soul", "枪手之魂", "铳手之魂"),
            ("Sluagh", "幽魂军团", "幽魂众"),
            ("Candy Bucket", "糖果桶", "糖桶"),
            ("Candy Monster", "糖果怪兽", "糖兽"),
            ("Spectrabbit", "幽灵兔", "幽兔"),
            ("Spectre", "大幽灵", "幽魅"),
            ("Starved Man", "饿殍", "饿殍"),
            ("Summoner", "召唤师", "召者"),
            ("Tampered Coffin", "捣毁之棺", "坏棺"),
            ("Dead Tree", "枯树", "枯木"),
            ("Disturbed Grave", "惊扰之墓", "扰墓"),
            ("Kennel", "犬舍", "犬舍"),
            ("Obelisk", "方尖碑", "方尖碑"),
            ("Shipwreck", "沉船残骸", "沉舟"),
            ("Flotsam", "浮木", "浮木"),
            ("Water Urn", "水瓮", "水瓮"),
            ("Voodoo Doll", "巫毒人偶", "巫蛊偶"),
            ("Tomb Robber", "盗墓贼", "盗冢者"),
            ("Ephialtes", "厄菲阿尔忒斯", "厄菲阿尔忒斯"),
            ("Otis", "奥提斯", "奥提斯"),
            ("Undertaker", "殡葬师", "殡者"),
            ("Walking Coffin", "行走之棺", "行棺"),
            ("Running Coffin", "奔走之棺", "奔棺"),
            ("Placeholder", "占位符", "虚位"),
            ("Vampire", "吸血伯爵", "饮血鬼"),
            ("Vellum", "羊皮纸", "韦牍"),
            ("Vengeful Spirit", "复仇之魂", "雠魂"),
            ("Warthr", "寒霜幽魂", "寒魄"),
            ("Wechuge", "威楚格", "威楚格"),
            ("Wight", "尸妖", "尸妖"),
            ("Will 'O' The Wisp", "鬼火", "鬼火"),
            ("Writher", "扭曲者", "蠕脊者"),
            ("Spiny Vertebrae", "尖刺脊椎骨", "棘脊骨"),
            ("Zombie", "丧尸", "僵尸"),
        };
    }
}
