using DiskCardGame;

namespace ClassicChineseLanguagePack
{
    internal static class InscryptionModsBatch32
    {
        private static void AddTranslation(string english, string classical)
        {
            ClassicChineseLanguagePackPlugin.Translate(
                ClassicChineseLanguagePackPlugin.GUID, null, english, classical, Language.ChineseSimplified);
        }

        public static void RegisterTranslations()
        {
            // P03InKayceesModMod - abilities, cards, challenges, achievements, etc.

            // Ability
            AddTranslation("Double Death", "双死");
            AddTranslation("Head Shot", "爆头");
            AddTranslation("[creature] is immune to the effects of Touch of Death, Stinky, and fire.", "[creature]不受死触、恶臭与火之效。");
            AddTranslation("If [creature]'s owner controls no Gem Vessels, [creature] perishes.", "若[creature]之主持无玛珂皿，[creature]死。");
            AddTranslation("Mine Cryptocurrency", "掘密币");
            AddTranslation("When part of a conduit, [creature] will generate cryptocurrency.", "处渠中时，[creature]生密币。");
            AddTranslation("Stamp Paperwork", "盖章");
            AddTranslation("Pay 1 Energy to stamp this paperwork as properly filed and ready for further processing.", "费1能，盖此牍，使既归藏，可俟后治。");
            AddTranslation("Big Strike", "重击");
            AddTranslation("[creature] attacks all cards in all lanes opposing it, or attacks just the center opposing lane if there are no cards it can attack.", "[creature]尽攻其对诸列之牌；若无可攻者，则独击正中之对列。");
            AddTranslation("Multiverse Bomb Latch", "多元爆弹遗契");
            AddTranslation("When [creature] perishes, its owner chooses a creature in any universe to gain the Multiverse Detonator sigil.", "[creature]死，则持牌人于任一宇宙择一物，受多元引爆印。");
            AddTranslation("Multiverse Brittle Latch", "多元脆骨遗契");
            AddTranslation("When [creature] perishes, its owner chooses a creature in any universe to gain the Brittle sigil.", "[creature]死，则持牌人于任一宇宙择一物，受脆骨印。");
            AddTranslation("Multiverse Detonator", "多元引爆");
            AddTranslation("When [creature] dies, all adjacent cards in all universes are dealt 10 damage", "[creature]死，则诸宇宙中凡与之相邻之牌皆受10伤。");
            AddTranslation("Multiverse Full of Oil", "多元盈油");
            AddTranslation("When [creature] dies, it adds 3 health to the creature on either side and across from it in every universe.", "[creature]死，则诸宇宙中其左右与对位之物，命各加3。");
            AddTranslation("Multiverse Fully Loaded", "多元满载");
            AddTranslation("When [creature] dies, it leaves a permanent +1 attack bonus in the lane it occupied in every universe.", "[creature]死，则诸宇宙中其所居之列皆永益1威。");
            AddTranslation("Multiverse Guardian", "多元守者");
            AddTranslation("When an opposing creature is placed opposite to an empty space in any universe, [creature] will move to that empty space.", "任一宇宙中，敌物若陈于空位之对位，[creature]即越宇移据其位。");
            AddTranslation("Multiverse Burrower", "多元潜龙");
            AddTranslation("When an empty space would be struck, [creature] will cross universes to move to that space to receive the strike instead.", "空位将受击时，[creature]即越宇移其处代受之。");
            AddTranslation("Multiverse Null Conduit", "多元虚渠");
            AddTranslation("Circuits completed by [creature] are completed in every universe.", "凡[creature]所成回路，皆成于诸宇宙。");
            AddTranslation("Multiverse Mighty Leap", "多元高跃");
            AddTranslation("[creature] will leap across universes to block attacks that occur in this lane in any universe.", "[creature]越宇而跃，以御任一宇宙此列之攻。");
            AddTranslation("Multiverse Sentry", "多元哨者");
            AddTranslation("When a creature moves into the space opposing [creature] in any universe, they are dealt 1 damage.", "物若于任一宇宙移入[creature]之对位，则受1伤。");
            AddTranslation("Multiverse Shield Latch", "多元坚盾遗契");
            AddTranslation("When [creature] perishes, its owner chooses a creature in any universe to gain the Nano Armor sigil.", "[creature]死，则持牌人于任一宇宙择一物，受微铠印。");
            AddTranslation("Multiverse Sprinter", "多元疾趋");
            AddTranslation("At the end of the owner's turn, [creature] will move to the next universe.", "持牌人合终，[creature]移于次宇宙。");
            AddTranslation("Multiverse Strike", "多元击");
            AddTranslation("[creature] will strike each opposing space in every universe other than its own.", "[creature]击其本宇之外诸宇宙之对位。");
            AddTranslation("Multiverse Great Mox", "多元至尊玛珂");
            AddTranslation("When [creature] is played, a Green, Orange, and Blue Gem is provided to the owner's side in every universe.", "[creature]既陈，则诸宇宙中持牌人之侧场各得绿、橙、蓝玛珂各一。");
            AddTranslation("Multiverse Hoarder", "多元聚藏");
            AddTranslation("When [creature] is played, you may search the multiverse for a card that has perished that is capable of traversing the multiverse.", "[creature]既陈，可搜多元，求一已死而能越宇之牌。");

            // Card
            AddTranslation("Mega Gunner", "巨铳手");
            AddTranslation("Triple Gunner", "三联铳手");
            AddTranslation("Hurt-n-Heal Conduit", "伤疗渠");
            AddTranslation("50er", "五十号");
            AddTranslation("Scrap Pile", "废料堆");
            AddTranslation("ALPHA.DOC", "甲文.DOC");
            AddTranslation("BETA.DOC", "乙文.DOC");
            AddTranslation("GAMMA.DOC", "丙文.DOC");
            AddTranslation("Basic Token", "凡筹");
            AddTranslation("Improved Token", "良筹");
            AddTranslation("Rare Token", "罕筹");
            AddTranslation("Blockchain", "区块链");
            AddTranslation("GollyCoin", "乖乖币");
            AddTranslation("Stupid-Ass Ape", "愚猿");
            AddTranslation("Fungible Ape", "可易猿");
            AddTranslation("Terminally Online Ape", "溺网猿");
            AddTranslation("AI Generated Ape", "机生猿");
            AddTranslation("Wholesome Ape", "淳猿");
            AddTranslation("Investment Ape", "贾猿");
            AddTranslation("Inquisitive Ape", "好问猿");
            AddTranslation("Endangered Ape", "危猿");
            AddTranslation("Bored Ape", "倦猿");
            AddTranslation("Annoyed Ape", "躁猿");
            AddTranslation("Sexy Ape", "妖猿");
            AddTranslation("Tech Ape", "机巧猿");
            AddTranslation("Broseph Ape", "兄猿");
            AddTranslation("Overgrown Ape", "蔓生猿");
            AddTranslation("Fancy Ape", "华猿");
            AddTranslation("Expensive Ape", "贵猿");
            AddTranslation("Scandalous Ape", "恶名猿");
            AddTranslation("Medium Ape", "中猿");
            AddTranslation("Personal Ape", "私猿");
            AddTranslation("Non-Fungible Ape", "不可易猿");
            AddTranslation("Trimmed Ape", "修猿");
            AddTranslation("Golly Ape", "乖乖猿");
            AddTranslation("Devious Ape", "狡猿");
            AddTranslation("Grape Ape", "葡萄猿");
            AddTranslation("UNSAFE.DAT", "危险.DAT");
            AddTranslation("Bug", "虫");
            AddTranslation("Virus Scanner", "毒省器");
            AddTranslation("Curve Hopper Hopper", "越曲越者");
            AddTranslation("Training Dummy", "习偶");
            AddTranslation("Blood Vessel", "血皿");
            AddTranslation("Spring Vessel", "簧皿");
            AddTranslation("Conduit Vessel", "渠皿");
            AddTranslation("Dredging Vessel", "浚皿");
            AddTranslation("Turbo Vessel", "疾皿");
            AddTranslation("Turbo Sapphire Vessel", "疾蓝玉皿");
            AddTranslation("Turbo Ruby Vessel", "疾红玉皿");
            AddTranslation("Turbo Emerald Vessel", "疾绿玉皿");
            AddTranslation("Turbo Blood Vessel", "疾血皿");
            AddTranslation("Turbo Spring Vessel", "疾簧皿");
            AddTranslation("Turbo Conduit Vessel", "疾渠皿");
            AddTranslation("Turbo Dredging Vessel", "疾浚皿");
            AddTranslation("L33pb0t", "跃机人");
            AddTranslation("Turbo L33pb0t", "疾跃机人");
            AddTranslation("Tree", "木");
            AddTranslation("Mole Man", "鼹人");
            AddTranslation("MAGBRUSH.EXE", "蔓尼笔.EXE");
            AddTranslation("GRIMQUIL.EXE", "格里羽笔.EXE");
            AddTranslation("Firewall", "火障");
            AddTranslation("Replicating Firewall", "孳火障");
            AddTranslation("Hunter Brain", "购捕者脑");
            AddTranslation("Activated Hunter", "启购捕者");
            AddTranslation("yarr.torrent", "海盗.torrent");
            AddTranslation("R!V3R 5N4PP3R", "机鳄龟");
            AddTranslation("M013", "机鼹");
            AddTranslation("R488!7", "机兔");
            AddTranslation("M4N7!5", "机螳");
            AddTranslation("41PH4", "机魁狼");
            AddTranslation("Robopossum", "机负鼠");
            AddTranslation("Grandpa:Clock", "钟翁");
            AddTranslation("Ghoulware", "鬼件");
            AddTranslation("Mox Obelisk", "玛珂尖碑");
            AddTranslation("Conduit Tower", "渠塔");
            AddTranslation("Radio Tower", "讯塔");
            AddTranslation("Generator", "机枢");
            AddTranslation("Power Sink", "纳能枢");
            AddTranslation("Failed Experiment", "败试物");
            AddTranslation("Heal Conduit", "疗渠");
            AddTranslation("Experiment #1", "试物一号");
            AddTranslation("Skeleton Master", "枯骨师");
            AddTranslation("M0l0t0v", "火油弹");
            AddTranslation("B30WULF", "钢狼");
            AddTranslation("PYTH0N", "铁脊蟒");
            AddTranslation("Asmanteus", "拟螳");
            AddTranslation("SeedBot", "种机人");
            AddTranslation("Conveyor Latcher", "传带遗契者");
            AddTranslation("Sky Latcher", "凌空遗契者");
            AddTranslation("W0rm", "机蠕");
            AddTranslation("Fishbones", "鱼骨");
            AddTranslation("Koi", "锦鲤");
            AddTranslation("Salmon", "鲑");
            AddTranslation("B3A5T GR4ND M4ST3R", "机兽大宗");
            AddTranslation("B3A5T M4ST3R", "机兽师");
            AddTranslation("T4URU5", "机牛");
            AddTranslation("SearchBot", "索机人");
            AddTranslation("AmmoBot", "弹机人");
            AddTranslation("Oil Jerry", "油杰瑞");
            AddTranslation("Necronomaton", "死灵机偶");
            AddTranslation("Zombie Process", "僵序");
            AddTranslation("AngelBot", "天使机人");
            AddTranslation("Conduit Protector", "渠卫");
            AddTranslation("Skel-E-Cell", "枯骨电匣");
            AddTranslation("Airspace Conduit", "霄渠");
            AddTranslation("Foul Conduit", "秽渠");
            AddTranslation("Spyplane", "谍机");
            AddTranslation("Executor", "行刑者");
            AddTranslation("Copypasta", "摹帖");
            AddTranslation("FrankenCell", "缝尸电匣");
            AddTranslation("Mr:Clock", "钟君");
            AddTranslation("Roboducky", "鸭机");
            AddTranslation("Ruby Titan", "红玉巨灵");
            AddTranslation("Sapphire Titan", "蓝玉巨灵");
            AddTranslation("Emerald Titan", "绿玉巨灵");
            AddTranslation("Swapper Latcher", "易位遗契者");
            AddTranslation("Box Bot", "匣机人");
            AddTranslation("Scrap Bot", "废机人");
            AddTranslation("Zip Bomb", "缩爆");
            AddTranslation("R4M", "机羝");
            AddTranslation("Elektron", "电机人");
            AddTranslation("Billdozer", "推土者");
            AddTranslation("Librarian", "司书");
            AddTranslation("Ruby Sentinel", "红玉哨");
            AddTranslation("Emerald Sentinel", "绿玉哨");
            AddTranslation("Sapphire Sentinel", "蓝玉哨");
            AddTranslation("Ignitron", "燃机人");
            AddTranslation("GlowBot", "辉机人");
            AddTranslation("Gas Conduit", "气渠");
            AddTranslation("Revignite", "复燃者");
            AddTranslation("Street Sweeper", "扫衢者");
            AddTranslation("Shield Smuggler", "私盾者");
            AddTranslation("Pity Seeker", "乞怜者");
            AddTranslation("Urch1n Conduit", "海胆渠");
            AddTranslation("Rh1n0", "机犀");
            AddTranslation("3leph4nt", "机象");
            AddTranslation("Jimmy Jr.", "小吉米");
            AddTranslation("OP Bot", "监机人");
            AddTranslation("Weeper", "泣者");
            AddTranslation("Sui-Cell", "自毁电匣");
            AddTranslation("Bedazzling Conduit", "眩渠");
            AddTranslation("G0ph3r", "鼹机");
            AddTranslation("P00dl3", "卷毛犬机");
            AddTranslation("Flamecharmer", "驯火者");
            AddTranslation("Artillery Droid", "炮机人");
            AddTranslation("Ultra Bot", "极机人");
            AddTranslation("Hellfire Commando", "狱火锐士");
            AddTranslation("Energy Vampire", "吮能鬼");
            AddTranslation("Orange Juicer", "橙榨机");
            AddTranslation("Dr Zambot", "赞博特博士");
            AddTranslation("Chippy", "碎碎");
            AddTranslation("L33pB0t Neo", "尼奥跃机");
            AddTranslation("Encapsulator", "封缄机");
            AddTranslation("Sir Blast", "爆爵");
            AddTranslation("Tapeworm", "绦虫机");
            AddTranslation("Lockjaw Cell", "锁颚电匣");
            AddTranslation("Replica Bleene", "蓝绿橙摹器");
            AddTranslation("Replica Orlu", "橙蓝绿摹器");
            AddTranslation("Replica Goranj", "绿橙蓝摹器");
            AddTranslation("Gem Auger", "钻玉机");
            AddTranslation("Sparkplug Cell", "火塞电匣");
            AddTranslation("Splice Conduit", "接渠");
            AddTranslation("49er", "四十九号");
            AddTranslation("Sentry Drone", "哨飞械");
            AddTranslation("Bolthound", "螺栓犬");
            AddTranslation("Explode Bot", "爆机人");
            AddTranslation("Null Conduit", "虚渠");
            AddTranslation("Multi Gunner", "多铳手");
            AddTranslation("Mox Module", "玛珂枢");
            AddTranslation("Bomb Latcher", "爆弹遗契者");
            AddTranslation("Shield Latcher", "坚盾遗契者");
            AddTranslation("Skel-E-Latcher", "枯骨遗契者");
            AddTranslation("L33pBot", "跃机人");
            AddTranslation("DummyCard", "哑牌");
            AddTranslation("Painbot", "苦机");
            AddTranslation("Melter", "冶者");
            AddTranslation("Dogbot", "犬机");

            // Consumable
            AddTranslation("Please! You've got to help me get out of here!", "求汝矣！速助我出此！");
            AddTranslation("Thank you! I hope he doesn't notice me here...", "谢矣！冀彼勿觉我在此……");
            AddTranslation("Thank you!", "谢矣！");
            AddTranslation("So much power, but so much pain...", "力甚盛，而苦亦甚……");
            AddTranslation("Good riddance to that little freak.", "彼小怪既去，善矣。");
            AddTranslation("Goobert", "黏伯特");
            AddTranslation("Please! You've got to help me get out of here!", "求汝矣！速助我出此！");
            AddTranslation("Data Cube", "数方");
            AddTranslation("Can be placed on the scales for some damage, if you're into that sort of thing.", "可置于衡，以致少伤；卿若好此。");
            AddTranslation("Laser Rifle", "激光铳");
            AddTranslation("This will give one of your cards the Sniper sigil for the rest of the battle. It's a gun - what else do you want?", "此可使卿一牌于此战得狙者之印。此乃铳也，卿复何求？");
            AddTranslation("Amplification Coil", "增幅匝");
            AddTranslation("Increases your max energy by 2. I suppose you can find some use for this.", "能上限增2。卿盖自知其用。");
            AddTranslation("UFO", "UFO");
            AddTranslation("Abducts a card of your choice. It gets the job done I suppose", "劫卿所择之一牌。聊足济事。");
            AddTranslation("Wiseclock", "智钟");
            AddTranslation("It rotates the board clockwise or something. I stole it from Leshy. Do you think he'll notice?", "可使场顺时而旋，盖如是。咱自莱西处窃之。卿谓彼将觉乎？");

            // Rule
            AddTranslation("I play a Mr:Clock", "咱陈一钟君");
            AddTranslation("a random card becomes a fish", "一偶牌化鱼");
            AddTranslation("1 of your lanes catches fire", "乃一列被焚");

            // Mode
            AddTranslation("Traps", "阱");
            AddTranslation("It seems there are some [c:bR]traps[c:] here", "此间似有数[c:bR]阱[c:]。");
            AddTranslation("Your bots will have to fight past them to get to me", "卿之机人须斗过之，乃得及我。");
            AddTranslation("Random Rule", "偶律");
            AddTranslation("For this battle, I'm going to add an additional rule.", "此战，咱将益一律。");
            AddTranslation("Conveyor", "输带");
            AddTranslation("It appears someone activated the [c:bR]conveyor belt[c:]", "似有人启[c:bR]输带[c:]矣。");
            AddTranslation("Cards will rotate clockwise every turn", "诸牌每合皆顺时轮。");
            AddTranslation("Explosive", "爆裂");
            AddTranslation("Hm; it looks like the cards in this battle will [c:bR]explode[c:] when they die", "唔，此战之牌死则[c:bR]爆[c:]。");
            AddTranslation("That seems dangerous", "此甚殆也。");
            AddTranslation("Stickers", "贴符");
            AddTranslation("See those [c:bR]stickers[c:]? They give my cards extra abilities.", "见彼[c:bR]贴符[c:]乎？能益咱之牌以别技。");
            AddTranslation("You don't mind an extra challenge, do you?", "卿不惮其难乎？");
            AddTranslation("Missiles", "飞弹");
            AddTranslation("Oh, there appears to be a malfunctioning missile launcher here", "噫，此间似有一失常之飞弹机。");
            AddTranslation("Watch out for rogue missile strikes I guess", "慎流弹妄击。");
            AddTranslation("Final Boss", "终魁");
            AddTranslation("Description for the Final Boss challenge", "终魁挑战之述");
            AddTranslation("Missing Remote", "失遥器");
            AddTranslation("You do not start with Mrs. Bomb's Remote", "始无弹夫人之遥器。");
            AddTranslation("Turbo Vessels", "疾皿");
            AddTranslation("Your vessels have the Double Sprinter sigil.", "卿之诸皿皆著双趋之印。");
            AddTranslation("Broken Bridges", "断桥");
            AddTranslation("Only two regions are available at the start of each run", "每局始惟二域可行。");
            AddTranslation("Pricey Upgrades", "贵升");
            AddTranslation("All upgrades cost more", "诸升级皆益贵。");
            AddTranslation("Eccentric Painter", "怪画者");
            AddTranslation("All bosses start with a random canvas rule.", "诸魁皆以一偶画缣律始。");
            AddTranslation("Energy Hammer", "能锤");
            AddTranslation("The hammer now costs 2 energy to use", "今用锤费2能。");
            AddTranslation("Costly Respawn", "贵复出");
            AddTranslation("The cost for additional respawns is tripled", "益复出之费三倍。");
            AddTranslation("Leaping Side Deck", "跃副牌列");
            AddTranslation("Replace your Empty Vessels with L33pbots.", "以跃机人易卿之虚皿。");
            AddTranslation("Wanted Fugitive", "购逋");
            AddTranslation("Your bounty level is permanently increased by 2", "购级永增2。");
            AddTranslation("Strange Encounters", "异遇");
            AddTranslation("Some battles on each map will have additional effects", "每图数战别有异效。");
            AddTranslation("The Great Transcendence", "大陟");
            AddTranslation("Unlock the secrets of the Great Transcendence", "启大陟之秘。");

            // SetText
            AddTranslation("ENTER NAME HERE", "于此书名");
            AddTranslation("Reset: $1", "复置：$1");

            // Achievement
            AddTranslation("P03 In Kaycee's Mod", "凯茜补中之鉟零三");
            AddTranslation("Uber Apocalypse", "极劫");
            AddTranslation("Beat \"P03 in Kaycee's Mod\" for the first time", "首胜“凯茜补中之鉟零三”");
            AddTranslation("Scarlet Skull", "绛髑");
            AddTranslation("Win a run with every challenge skull from the first page enabled", "启首页诸挑战髑而竟一局。");
            AddTranslation("Avatar", "化身");
            AddTranslation("Take ownership of one of G0lly's beloved trinkets", "取乖乖所珍一玩为己有。");
            AddTranslation("Book of the Dead", "冥书");
            AddTranslation("During The Archivist's boss fight, survive 6 turns during phase 2", "于典牍者魁战之二相存6合。");
            AddTranslation("Feral Spirit", "野魂");
            AddTranslation("Defeat the Photographer without using the camera", "不用影器而败取影者。");
            AddTranslation("Gallery Showcase", "廊陈");
            AddTranslation("Create an infinite loop in the Unfinished Boss fight", "于未竟之魁战作无穷环。");
            AddTranslation("Battle Frenzy", "战狂");
            AddTranslation("Destroy 30 Bounty Hunters in your lifetime", "平生毁购捕者30。");
            AddTranslation("Calling for Backup", "呼援");
            AddTranslation("Complete all NPC quests that appear in a single run", "一局而毕所遇诸人之求。");
            AddTranslation("Accelerated Fuse", "疾燧");
            AddTranslation("Skeleclock and destroy a card given to you by an NPC", "使一所遇之人予卿之牌骸机化而毁之。");
            AddTranslation("Mana Blink", "法烁");
            AddTranslation("Have six energy available on turn two", "次合可用之能有6。");
            AddTranslation("Aimless Assault", "妄攻");
            AddTranslation("Earn 15 Robobucks in a single battle", "一战得机币15。");
            AddTranslation("Rebuild From Scrap", "废余复构");
            AddTranslation("Have a card in your deck that is gemified, skeleclocked, transformable, and can complete a circuit", "卿之牌列有一牌，既玉化，又骸机化，可变而能成回路。");
            AddTranslation("Buy Your Buddy", "购友");
            AddTranslation("Give a card with the maximum amount of SP to the Bot Builder", "以数点极满之牌予造机者。");
            AddTranslation("Me Smash", "我击之");
            AddTranslation("Strike P03 six separate times in a single turn", "一合六击鉟零三。");
            AddTranslation("Absolution", "解罪");
            AddTranslation("Have the scales tilted 4 points against you on three different turns", "三异合，令衡向卿偏4。");
            AddTranslation("The Perfect Crime", "无迹之罪");
            AddTranslation("Win five battles with bounty hunters without killing them", "不杀购捕者而胜5战。");
            AddTranslation("Blastenheimer 5000 Ultra Cannon", "爆能5000极炮");
            AddTranslation("Deal 6 damage with Plasma Jimmy in a single turn", "一合以等离吉米伤6。");
            AddTranslation("Double Time", "倍时");
            AddTranslation("Skeleclock every card in your deck", "卿之牌列诸牌尽骸机化。");
            AddTranslation("One And The Same", "一而同");
            AddTranslation("Complete the Mycologist's experiment and create an abomination of science", "毕蕈家之验，而作一畸物。");
            AddTranslation("Burning Adrenaline", "燃激");
            AddTranslation("Repair the generator in four turns or less", "4合内修机枢。");
            AddTranslation("Carnival Clown", "嘉会优");
            AddTranslation("Achieve a high score of 50 or more on the test of strength", "于力试得高分50以上。");
            AddTranslation("Verse Riff", "叠宙");
            AddTranslation("Understand the true meaning of the Great Transcendence", "知大陟之真义。");

            // Starter
            AddTranslation("Vanilla", "原味");
            AddTranslation("Bomb", "炸弹");
            AddTranslation("Shield", "护盾");
            AddTranslation("Random", "随机");
            AddTranslation("Conduit", "渠");
            AddTranslation("Evolve", "进化");
            AddTranslation("Gems", "宝石");
            AddTranslation("Stall", "拖延");
            AddTranslation("Annoying", "烦人");
            AddTranslation("Fire", "火焰");
            AddTranslation("Recharge", "充能");
            AddTranslation("NoCharge", "无充能");
            AddTranslation("Swap", "交换");
            AddTranslation("Nefarious", "邪恶");
            AddTranslation("Cheapo", "廉价");
            AddTranslation("FullDraft", "全选");

            // StatLabel
            AddTranslation("Energy Expended", "耗能总量");
            AddTranslation("Hammer Blows Dealt", "锤击总次数");
            AddTranslation("Abominations Created", "创造之畸形物数");
            AddTranslation("Quests Completed", "任务完成数");
            AddTranslation("Bounty Hunters Killed", "购捕者击杀数");

            // Mod
            AddTranslation("Special Hammer Mod", "异锤补");
            AddTranslation("Incredible Drafting Mod", "妙选牌补");
            AddTranslation("The Community API", "众社API");
            AddTranslation("Super-Duper Unity Editor", "无双Unity编器");

            // Pack
            AddTranslation("Kaycee's P03 Expansion Pack #1", "凯茜鉟零三扩包其一");
            AddTranslation("The first expansion pack from the developers of 'P03 in Kaycees Mod' adds [count] new cards across all four regions of Botopia.", "“凯茜补中之鉟零三”作者之首扩包，益[count]新牌于机托邦四域。");
            AddTranslation("Kaycee's P03 Expansion Pack #2", "凯茜鉟零三扩包其二");
            AddTranslation("The second official expansion pack, with [count] firey new cards that command an explosive reaction!", "官第二扩包，内有[count]炽新牌，足致爆应！");
            AddTranslation("Inscryption: Rogue Bots of Botopia", "《冥锲》：机托邦叛机人");
            AddTranslation("Botopia has become overrun with rogue bots! These [count] encounters have been rebalanced for Kaycee's Mod.", "机托邦为叛机人所横据！此[count]遇战皆为凯茜补而更平。");
            AddTranslation("Kaycee's P03 Encounter Expansion #1", "凯茜鉟零三遭遇扩包其一");
            AddTranslation("[count] additional encounters that feature cards from the first official P03 expansion pack.", "益[count]遇战，皆用鉟零三首官扩包之牌。");
            AddTranslation("Kaycee's P03 Encounter Expansion #2", "凯茜鉟零三遭遇扩包其二");
            AddTranslation("[count] additional encounters that feature cards from the second official P03 expansion pack.", "益[count]遇战，皆用鉟零三次官扩包之牌。");

            // Bounty
            AddTranslation("LIONEL", "莱昂");
            AddTranslation("LOUIS", "路易");
            AddTranslation("LOU", "卢");
            AddTranslation("JAMES", "詹姆");
            AddTranslation("PARTS", "零件");
            AddTranslation("JIMMY", "吉米");
            AddTranslation("KLAXON", "警号");
            AddTranslation("POE", "坡");
            AddTranslation("DANNY", "丹尼");
            AddTranslation("MULLINS", "马林");
            AddTranslation("LUKE", "卢克");
            AddTranslation("BOMB", "炸弹");
            AddTranslation("KARD", "卡德");
            AddTranslation("BRICK", "砖");
            AddTranslation("SMACK", "击");
            AddTranslation("HACK", "骇");
            AddTranslation("BRASH", "莽");
            AddTranslation("ZACK", "扎克");
            AddTranslation("BOOM", "轰");
            AddTranslation("ROCKET", "火箭");
            AddTranslation("SNILL", "斯尼尔");
            AddTranslation("ZAP", "电");
            AddTranslation("HOTS", "炽");
            AddTranslation("BURNER", "燃者");
            AddTranslation("DE-", "德-");
            AddTranslation("DU", "杜");
            AddTranslation("DER", "德尔");
            AddTranslation("VAN DER", "范德");
            AddTranslation("BA", "巴");
            AddTranslation("FAIR", "费尔");
            AddTranslation("DO", "多");
            AddTranslation("STER", "斯特");
            AddTranslation("STAIN", "斯坦");
            AddTranslation(".EXE", ".EXE");
            AddTranslation("EMA", "埃玛");
            AddTranslation("EVSKI", "耶夫斯基");
            AddTranslation("EZ", "埃兹");
            AddTranslation("ON", "昂");
            AddTranslation("ALOT", "阿洛特");
        }
    }
}
