using DiskCardGame;

namespace ClassicChineseLanguagePack
{
    internal static class InscryptionModsBatch27
    {
        private static void AddTranslation(string english, string classical)
        {
            ClassicChineseLanguagePackPlugin.Translate(
                ClassicChineseLanguagePackPlugin.GUID, null, english, classical, Language.ChineseSimplified);
        }
        public static void RegisterTranslations()
        {
            // AllTheSigilsMod (part 1)
            AddTranslation("Kill [creature].", "杀[creature]。");
            AddTranslation("Sharpen", "砺");
            AddTranslation("If you have an orange mox gem, sacrifice it to give [creature] +1 attack power.", "若汝有橙玛珂，可祀之，使[creature]威加一。");
            AddTranslation("[creature] sacrifices an orange gem to sharpen it's attack!", "[creature]祀橙玉，以砺其击！");
            AddTranslation("Spellsword", "术剑");
            AddTranslation("All gems on the same side of the board as[creature] gain 2 power, attack, and perish.", "与[creature]同侧局上诸玉，威益二，出击而死。");
            AddTranslation("Trained Flier", "习翔");
            AddTranslation("Grant [creature] the effect of the Airborne sigil until next upkeep. If the card already has Airborne, this will remove it's effect until next upkeep.", "使[creature]至次合始得翔袭印契；若此牌素有之，则反去其效至次合始。");
            AddTranslation("Trained Swimmer", "习潜");
            AddTranslation("Creature will gain the effect of the Waterborne sigil for one turn.", "[creature]一合得潜袭印契。");
            AddTranslation("Upgrade Subroutine", "升程");
            AddTranslation("When[creature] destroys another bot, this gains 1 point. When activated, the owner is presented with a choice of three sigils to permanently augment the card. Selecting a sigil spends points, and the more points accumulated when the sigil is activated, the higher quality the presented sigils will be.", "凡[creature]毁他机人，则积一点。启之，则持牌者于三印契中择一，以永益此牌。择印耗点；积点愈多，则所示印契愈良。");
            AddTranslation("Aculeate Grip", "螫攫");
            AddTranslation("When a creature is played on the same side of the board as [creature], [creature] will move towards them as far as possible, dealing them one damage and increasing it's own health by 1.", "他物既陈于与[creature]同侧之局，[creature]即尽所能趋之，伤彼一，而自命益一。");
            AddTranslation("Allure", "媚引");
            AddTranslation("At the end of the round, [creature] will draw opposing creatures in front of itself.", "每轮终，[creature]引敌物于其前。");
            AddTranslation("Annihilation", "殄灭");
            AddTranslation("When [creature] perishes, all creatures on the board are dealt 10 damage.", "[creature]死，则局上诸物皆受十伤。");
            AddTranslation("Ant Guardian", "护蚁");
            AddTranslation("[creature] will deal damage equal to it's attack power to any card which strikes a friendly ant.", "己蚁见击，则[creature]以其威伤击者。");
            AddTranslation("Antimagic", "反术");
            AddTranslation("Any mox gems played while [creature] is on the board will immediately perish. [creature] will move to the position of the destroyed gem, gain 1 health, and immediately attack.", "凡[creature]在局，所陈玛珂玉即死。[creature]移据其毁玉之处，命益一，而即击。");
            AddTranslation("[creature] destroys the played gem!", "[creature]毁其所陈之玉！");
            AddTranslation("Armortify", "被甲");
            AddTranslation("When [creature] attacks an opposing creature and it perishes, this card gains the armored sigil.", "[creature]击杀敌物，则此牌得坚甲印契。");
            AddTranslation("Artistic License", "艺纵");
            AddTranslation("When [creature] is played, the creature opposing it loses all sigils.", "[creature]既陈，其对物失其诸印。");
            AddTranslation("Trying to plunder me sigils? Yer a sour spoilsport!", "欲掠我印耶？汝真败兴之徒！");
            AddTranslation("Despite your artistry, the soul of the moon is impervious...", "虽工于艺，然月魂不可犯……");
            AddTranslation("Backup", "后继");
            AddTranslation("When [creature] perishes by combat, the first card in it's owner's hand is played in it's place.", "[creature]战死，则持牌者手中首牌代居其处。");
            AddTranslation("[creature] calls in backup.", "[creature]召后继矣。");
            AddTranslation("Bandage Weaver", "纫帛者");
            AddTranslation("At the end of the turn,[creature] will heal the cards to it's left and right for 1 health.", "合终，[creature]疗左右诸牌各一命。");
            AddTranslation("Bastion", "垒");
            AddTranslation("When [creature] recieves damage, it only takes half the damage it normally would, rounded up.", "[creature]受伤，所受惟常半，分奇则进一。");
            AddTranslation("Batch Delete", "并删");
            AddTranslation("When [creature] strikes a creature and it perishes, any creatures on the board which share the same cost as the target perish also.", "[creature]击物而杀之，则局上凡与其同直之物亦皆死。");
            AddTranslation("[creature] shreds any other cards with the same cost as it's victim...", "[creature]尽裂诸与所害者同直之牌……");
            AddTranslation("Bejeweled", "连玉");
            AddTranslation("While [creature] is on the field, lining up three gems of the same colour will remove those gems from the field. Any creatures which opposed those gems will be removed as well, and the opponent will take damage directly equal to their combined attack power. ", "凡[creature]在局，三同色之玉若成列，则去此诸玉。凡与之相对之物亦去之；敌并直受其合威之伤。");
            AddTranslation("Bewilder", "惑");
            AddTranslation("When [creature] is played, it's owner may choose any creature. Swap that creatures power and health.", "[creature]既陈，持牌者可择一物，而易其威与命。");
            AddTranslation("Bifurcated When Gempowered", "得玉歧击");
            AddTranslation("If its owner has an Orange Gem, [creature] will strike each opposing space to the left and right of the space across from it.", "若持牌者有橙玉，[creature]击其正对之左与右。");
            AddTranslation("Bisection", "二裂");
            AddTranslation("When [creature] kills another creature, two copies of the victim are created in the owner's hand with zero power and halved health.", "[creature]杀他物，则持牌者手中生受害者之同牌二，威皆为零，而命半之。");
            AddTranslation("Bleach", "漂液");
            AddTranslation("When [creature] is played, all opponent creatures lose all sigils.", "[creature]既陈，敌诸物尽失其诸印。");
            AddTranslation("Bloated", "丰血");
            AddTranslation("[creature] is worth blood equal to its health when sacrificed.", "[creature]祀时，其值血如其命。");
            AddTranslation("Blood Artist", "血绘者");
            AddTranslation("Every three cards which perish by combat while [creature] is on the board, [creature] will give it's owner a deathcard constructed from the cost, stats, and sigils of those creatures.", "凡[creature]在局，战死之牌每三，则[creature]为持牌者作一死牌，因其诸物之直、数与印契而成之。");
            AddTranslation("[creature] constructs a deathcard from previous creatures deaths...", "[creature]因先死诸物而作一死牌……");
            AddTranslation("When [creature] is sacrificed, it transforms to or from it's alternate form instead of perishing.", "[creature]祀之，则不死，而与其异相相易。");
            AddTranslation("Blood Dependent", "恃血");
            AddTranslation("If [creature] does not strike another creature during the attack phase, it will perish at the start of the owner's next turn.", "若[creature]攻时不击他物，则持牌者次合始必死。");
            AddTranslation("Blood From Stone", "石出血");
            AddTranslation("You may sacrifice terrain cards in order to play [creature].", "可祀地形牌，以陈[creature]。");
            AddTranslation("Blood Gusher", "涌血");
            AddTranslation("When [creature] attacks an opposing creature and it perishes, this card, as well as creatures to the left and right of this card, gain 1 health.", "[creature]击杀敌物，则此牌与左右邻物各命益一。");
            AddTranslation("Blood Guzzler", "饮血者");
            AddTranslation("When[creature] deals damage to a creature, it gains 1 Health for each damage dealt.", "[creature]出伤之时，每伤一，则命益一。");
            AddTranslation("[creature] consumes the blood of its prey!", "[creature]饮其猎之血！");
            AddTranslation("Blood Magic", "血术");
            AddTranslation("While [creature] is on the field, its owner may sacrifice any gems, even if those gems normally cannot be sacrificed.", "凡[creature]在局，持牌者可祀诸玉；纵其常不可祀，亦可。");
            AddTranslation("Bloodrunner", "血行");
            AddTranslation("When [creature] deals damage to a creature, it will move in the direction inscribed in the sigil.", "[creature]伤物，则循印所志之向而移。");
            AddTranslation("Blue Inspiration", "蓝悟");
            AddTranslation("While [creature] is on the board, all friendly creatures which cost a blue gem will gain a random sigil when played.", "凡[creature]在局，己物凡直蓝玉者既陈，皆得一偶印契。");
            AddTranslation("[creature] empowers the Blue Gem cost creature with a random sigil!", "[creature]使一直蓝玉之物得一偶印契！");
            AddTranslation("Bombjuration", "爆召");
            AddTranslation("When [creature] is played, it's owner may choose an empty slot on either side of the board. A magic bomb is created in the chosen slot.", "[creature]既陈，持牌者可择局中一空位，生一法爆于其所。");
            AddTranslation("Bombs Away", "投爆");
            AddTranslation("When [creature] is played, a Payload is created in the opposing slot. [define:SigilNevernamed Payload]", "[creature]既陈，则其对位生一载荷。[define:SigilNevernamed Payload]");
            AddTranslation("[creature] drops a payload into the opposing slot!", "[creature]投一载荷于其对位！");
            AddTranslation("Bone Dependent", "恃骨");
            AddTranslation("If the user has 0 Bones, [creature] will perish.", "若持牌者无骨，[creature]即死。");
            AddTranslation("Bone Duke", "骨公");
            AddTranslation("When [creature] dies, 3 Bones are awarded instead of 1.", "[creature]死，则所得之骨不一而三。");
            AddTranslation("Bonelust", "嗜骨");
            AddTranslation("When [creature] kills another creature, it generates 3 bones for its owner.", "[creature]杀他物，则为持牌者生三骨。");
            AddTranslation("Bone Spurs", "骨刺");
            AddTranslation("When [creature] is struck, it generates a bone for it's owner.", "[creature]见击，则为持牌者生一骨。");
            AddTranslation("[creature] will target the least powerful opposing card when it attacks.", "[creature]攻时，先击敌牌威最寡者。");
            AddTranslation("Burning", "焚");
            AddTranslation("At the end of the owner's turn, [creature] takes 1 damage. Also, when [creature] is struck, the striker gains this sigil.", "持牌者合终，[creature]受一伤；其见击也，击者亦得此印契。");
            AddTranslation("Buzz Off", "遗蜉");
            AddTranslation("At the end of the owner's turn, [creature] will move in the direction inscribed in the sigil and leave a mayfly in it's old place. A mayfly is defined as 1 power, 1 health, airborne, brittle.", "持牌者合终，[creature]循印所志之向而移，并遗一蜉蝣于故处。蜉蝣者：1威、1命、翔袭、脆骨。");
            AddTranslation("Call To Arms", "号战");
            AddTranslation("When [creature] is played, the creatures to it's left and right will immediately attack.", "[creature]既陈，其左右之物即击。");
            AddTranslation("Card Shedder", "遗牌");
            AddTranslation("At the end of the owner's turn, [creature] will move in the direction inscribed in the sigil and leave a card in it's wake.", "持牌者合终，[creature]循印所志之向而移，并遗一牌于其后。");
            AddTranslation("Caustic", "腐毒");
            AddTranslation("When [creature] perishes, it's killer perishes as well.", "[creature]死，则杀之者亦死。");
            AddTranslation("Center Strike", "中击");
            AddTranslation("[creature] will attack all opponent slots except for those in the leftmost and rightmost lanes.", "[creature]击诸敌位，惟最左与最右之列不击。");
            AddTranslation("Chaos Strike", "乱击");
            AddTranslation("When [creature] is drawn, this sigil is replaced by a random strike modifier sigil.", "[creature]既引，此印契偶易为一击类印契。");
            AddTranslation("Cheater", "诈者");
            AddTranslation("When [creature] attacks an opposing creature and it perishes, the opponent is dealt 1 damage.", "[creature]攻敌物而杀之，则其主受1伤。");
            AddTranslation("Circuit Maker", "成路");
            AddTranslation("When [creature] is played, a conduit card is created to its left and right.", "[creature]既陈，左右各生一渠牌。");
            AddTranslation("Claw", "爪");
            AddTranslation("[creature] will lose all attack power if it is not directly adjacent to a card bearing the clawed sigil.", "若[creature]不与负爪印之牌邻，则尽失其威。");
            AddTranslation("Clawed", "生爪");
            AddTranslation("When [creature] is played, claws are created to the left and right. Any creatures in those spaces will be killed.", "[creature]既陈，左右生爪；其位凡物，皆死。");
            AddTranslation("Clawing Hand", "爪手");
            AddTranslation("When [creature] is struck, the striker is dealt damage equal to the number of cards in the owner's hand.", "[creature]受击，则击者受持牌者手牌数之伤。");
            AddTranslation("Cleaving", "劈裂");
            AddTranslation("When [creature] strikes another creature, that creature will be cut in half. Half of the creature will move to the right, while the other half remains in place.", "[creature]击物，则劈之为二：其一右移，其一故处。");
            AddTranslation("[creature] cleaves it's target in half!", "[creature]劈其的为二！");
            AddTranslation("Coastguard", "海卫");
            AddTranslation("Submerges during the opponent's turn. When an opposing creature is placed opposite to an empty space, [creature] will move to that empty space while submerged.", "敌合则潜。若敌物陈于空位之对，[creature]潜而移据其空位。");
            AddTranslation("Collateral Damage", "旁伤");
            AddTranslation("At the end of the owner's turn, if [creature] is on the board, the nearest creature to this card will be dealt ten damage.", "持牌者合终，若[creature]在场，则距此牌最近之物受10伤。");
            AddTranslation("Collector", "敛者");
            AddTranslation("At the end of the owner's turn,[creature] will move in the direction inscribed on the sigil. Creatures in the way will be returned to the owner's hand.", "持牌者合终，[creature]循印所志而移。道中诸物，皆返其主持手。");
            AddTranslation("Commander", "将令");
            AddTranslation("When [creature] is struck, the creatures to it's left and right will attack the striker.", "[creature]受击，则其左右之物皆攻击者。");
            AddTranslation("Double Strike When Powered", "得能双击");
            AddTranslation("If [creature] is within a circuit, it will strike the opposing space an additional time when it attacks.", "若[creature]在回路中，则攻时加击其对位一次。");
            AddTranslation("Gift When Powered", "得能赐");
            AddTranslation("If [creature] is within a circuit when it perishes, a random card is created in your hand.", "若[creature]死时在回路中，则于汝手生一随机牌。");
            AddTranslation("Morsel When Powered", "得能一脔");
            AddTranslation("When[creature] is sacrificed while inside a completed circuit, ⁣it adds its stat values to the card it was sacrificed for.", "[creature]在成路中见祀，则以其威命附于所祀之牌。");
            AddTranslation("Omnipotent When Powered", "得能遍击");
            AddTranslation("If [creature] is within a circuit, it will strike every opposing space containing a card when it attacks. [creature] will strike directly if no creatures oppose it, or if it is not in a circuit.", "若[creature]在回路中，则攻时遍击敌侧有牌之位。若前无物，或不在回路中，则直击。");
            AddTranslation("Powered Quills", "得能利棘");
            AddTranslation("When [creature] is struck while inside a completed circuit, the striker is dealt 2 damage.", "[creature]在成路中受击，则击者受2伤。");
            AddTranslation("Print When Powered", "得能印玉");
            AddTranslation("If [creature] is inside a completed circuit, a gem will be created in its owners hand at the start of their turn.", "若[creature]在成路中，持牌者合始，于其手生一玉。");
            AddTranslation("[creature] prints a mox gem for its owner!", "[creature]为其主印出一玉！");
            AddTranslation("Repulsive When Powered", "得能可憎");
            AddTranslation("While [creature] is within a conduit, if another creature would strike it, it does not.", "[creature]在回路中，则他物欲击之而不能。");
            AddTranslation("Scavenge When Powered", "得能拾荒");
            AddTranslation("While [creature] is inside a completed circuit, opposing creatures also grant Bones upon death.", "[creature]在成路中，则敌物死亦授骨。");
            AddTranslation("Splash Damage When Powered", "得能溅伤");
            AddTranslation("While [creature] is within a conduit when it strikes a slot, creatures to the left and right of the struck slot will be dealt 1 damage.", "[creature]在回路中击一位时，其所击位左右诸物各受1伤。");
            AddTranslation("Stimulate When Powered", "得能激哉");
            AddTranslation("While [creature] is inside a completed circuit, it gains 2 health at the start of its owners turn.", "[creature]在成路中，则持牌者合始，其命加2。");
            AddTranslation("[creature] stimulates its health!", "[creature]益其命矣！");
            AddTranslation("Billowing Bond", "翔契");
            AddTranslation("Creatures within a bond completed by [creature] gain the power of flight at the start of each turn.", "[creature]所成契中之物，每合始皆得飞。");
            AddTranslation("Elder Conduit", "玉骨渠");
            AddTranslation("When a creature within a circuit completed by [creature] perishes, a Gem Skeleton will be created in it's place.", "凡在[creature]所成回路中而死之物，其处生一玉骨。");
            AddTranslation("[creature] calls forth a Gem Skeleton with the old magics!", "[creature]以古术召一玉骨！");
            AddTranslation("Emerald Conduit", "绿玉渠");
            AddTranslation("If [creature] is part of a completed circuit, its owner gains a green gem.", "若[creature]与成路，其主持有一绿玉。");
            AddTranslation("[creature] completes a circuit, and grants its owner a green gem!", "[creature]成一回路，而授其主一绿玉！");
            AddTranslation("[creature] no longer completes a circuit, and no longer grants a green gem!", "[creature]不复成回路，亦不复授绿玉！");
            AddTranslation("Friendship Bond", "友契");
            AddTranslation("Empty spaces within a bond completed by [creature] spawn Squirrels at the end of the owner's turn.", "[creature]所成契中之空位，持牌者合终皆生松鼠。");
            AddTranslation("Grave Conduit", "骨渠");
            AddTranslation("Completes a circuit. At the end of the owner's turn, [creature] will generate one bone for each creature contained within the circuit it completes.", "成回路。持牌者合终，[creature]以其所成回路中每物各生一骨。");
            AddTranslation("[creature] grants a bone for every creature in it's circuit.", "[creature]为其回路中每物授一骨。");
            AddTranslation("Gun Conduit", "铳渠");
            AddTranslation("When a creature moves into the slot opposing a card in a circuit completed by [creature], the moved creature is dealt 1 damage.", "凡物入于[creature]所成回路中牌之对位，则彼物受1伤。");
            AddTranslation("[creature] takes a free shot!", "[creature]得一先击！");
            AddTranslation("Hot Conduit", "灼渠");
            AddTranslation("When a creature within a circuit completed by [creature] is struck, the striker gains the Burning Sigil. Also, creatures within this card's circuit do not take damage from the Burning sigil.", "在[creature]所成回路中之物受击，则击者得燃印；且此回路中诸物不受燃印之伤。");
            AddTranslation("Loot Conduit", "掠渠");
            AddTranslation("Completes a circuit. At the start of the owner's turn, [creature] will draw 1 card to the owners hand for every empty space in the circuit it completes.", "成回路。持牌者合始，[creature]以其所成回路中每空位各抽一牌入主手。");
            AddTranslation("[creature] draws a card for every empty space in it's circuit!", "[creature]为其回路中每空位各引一牌！");
            AddTranslation("Malfunctioning Conduit", "故渠");
            AddTranslation("Completes a circuit. At the end of its owner's turn, random cards from its owners hand will be played in random spaces inside of the circuit completed by [creature]. Those cards gain the Burning Sigil.", "成回路。持牌者合终，自其手随机取牌，置于[creature]所成回路之空位；彼牌并得燃印。");
            AddTranslation("[creature] draws cards into it's circuit!", "[creature]引牌入其回路！");
            AddTranslation("Meaningless Bond", "虚契");
            AddTranslation("[creature] may complete a bond, but provides no additional effect.", "[creature]可成契，而别无所效。");
            AddTranslation("Nano Conduit", "甲渠");
            AddTranslation("At the end of its owners turn, creatures within a circuit completed by [creature] gain the Armored sigil.", "持牌者合终，凡在[creature]所成回路中之物皆得甲印。");
            AddTranslation("[creature] shields all creatures in its circuit!", "[creature]护其回路中诸物矣！");
            AddTranslation("Ruby Conduit", "红玉渠");
            AddTranslation("If [creature] is part of a completed circuit, its owner gains an orange gem.", "若[creature]与成路，其主持有一红玉。");
            AddTranslation("[creature] completes a circuit, and grants its owner an orange gem!", "[creature]成一回路，而授其主一红玉！");
            AddTranslation("[creature] no longer completes a circuit, and no longer grants an orange gem!", "[creature]不复成回路，亦不复授红玉！");
            AddTranslation("Sapphire Conduit", "蓝玉渠");
            AddTranslation("If [creature] is part of a completed circuit, its owner gains a blue gem.", "若[creature]与成路，其主持有一蓝玉。");
            AddTranslation("[creature] completes a circuit, and grants its owner a blue gem!", "[creature]成一回路，而授其主一蓝玉！");
            AddTranslation("[creature] no longer completes a circuit, and no longer grants a blue gem!", "[creature]不复成回路，亦不复授蓝玉！");
            AddTranslation("Stim Conduit", "激渠");
            AddTranslation("At the end of its owners turn, creatures within a circuit completed by [creature] gain 1 Health.", "持牌者合终，凡在[creature]所成回路中之物命加1。");
            AddTranslation("[creature] increases the health of every creature in it's circuit!", "[creature]益其回路中诸物之命矣！");
            AddTranslation("Tender Bond", "柔契");
            AddTranslation("Creatures within a bond completed by [creature] heal to full health at the start of the owner's turn.", "[creature]所成契中之物，持牌者合始皆复其全命。");
            AddTranslation("Thorny Conduit", "棘渠");
            AddTranslation("When a creature within a circuit completed by [creature] is struck, the striker is then dealt a single damage point.", "在[creature]所成回路中之物受击，则击者亦受1伤。");
            AddTranslation("Confusion", "乱");
            AddTranslation("When [creature] is played opposite an opponents creature, swap that creatures power and health.", "[creature]陈于敌物之对，则易彼物之威与命。");
            AddTranslation("The card opposing [creature] is confused!", "[creature]对位之牌乱矣！");
            AddTranslation("Copier", "摹印");
            AddTranslation("When [creature] perishes, a copy of it's murderer is created in your hand.", "[creature]死，则于汝手生一杀之者之副本。");
            AddTranslation("Coward", "怯");
            AddTranslation("When [creature] is targeted, it will leap out of the way.", "[creature]为攻击所指，则跃而避之。");
            AddTranslation("Crooked Strike Left", "偏左击");
            AddTranslation("[creature] will attack the space to the left of it's intended target.", "[creature]攻其所向之左位。");
            AddTranslation("Crooked Strike Right", "偏右击");
            AddTranslation("[creature] will attack the space to the right of it's intended target.", "[creature]攻其所向之右位。");
            AddTranslation("Crossbones", "十字骨");
            AddTranslation("When [creature] is played, it grants 2 bones to it's owner.", "[creature]既陈，则授其主2骨。");
            AddTranslation("Crunchy", "脆");
            AddTranslation("When [creature] is sacrificed, it generates one bone for its owner.", "[creature]见祀，则为其主生1骨。");
            AddTranslation("Cute", "可人");
            AddTranslation("Creatures that strike [creature] feel guilty, and will skip their next strike.", "击[creature]之物怀愧，而后一击遂阙。");
            AddTranslation("Data Breach", "泄机");
            AddTranslation("When [creature] perishes, its owner must draw a card from their deck and immediately discard it. The opponent is dealt damage equal to the drawn creatures attack power.", "[creature]死，则其主自牌列引一牌而立弃之。敌受其所引物威数之伤。");
            AddTranslation("Deadringer", "死铃");
            AddTranslation("While [creature] is alive and on the board, it gains +1 power each time the bell is rung, if it has less than 5 power.", "[creature]存于场而威未满5，则每铃鸣加1威。");
            AddTranslation("[creature] powers up!", "[creature]威益矣！");
            AddTranslation("Death Snatch", "死掠");
            AddTranslation("When [creature] perishes, draw a card from your deck.", "[creature]死，则自乃牌列引一牌。");
            AddTranslation("Decked Out", "具装");
            AddTranslation("When [creature] is struck, a card from a random temple's side deck is created in your hand.", "[creature]受击，则自随机神殿之副牌生一牌于汝手。");
            AddTranslation("Defiler", "污者");
            AddTranslation("When [creature] perishes, its owner must draw a card from their deck and immediately discard it.", "[creature]死，则其主自牌列引一牌而立弃之。");
            AddTranslation("Desperate", "穷搏");
            AddTranslation("When [creature] perishes, it deals one point of damage to the opponent.", "[creature]死，则遗1伤于敌。");
            AddTranslation("[creature] deals a free point of damage as it perishes.", "[creature]死而遗1伤于敌。");
            AddTranslation("Deus Hoof", "鹿神");
            AddTranslation("All friendly hooved creatures gain +1 Power and Health while [creature] is on the board. Also, all hooved creatures will attack anything that strikes [creature].", "[creature]在场，则诸有蹄之友物皆加1威1命。凡击[creature]者，亦为诸蹄物所攻。");
            AddTranslation("Dexter Strike", "右前击");
            AddTranslation("[creature] will also strike the slot to the right of the opposing slot when it attacks.", "[creature]攻时，亦击对位之右格。");
            AddTranslation("Diagonal Strike", "斜击");
            AddTranslation("When [creature] attacks, it will strike either to the left or right of its original target, prioritising striking slots containing creatures. If both or neither slots adjacent to the target contain creatures, [creature] will attack to the left or right at random.", "[creature]攻时，或击其本的之左，或击其右，先择有物者。若两侧俱有，抑俱无，则左右随机。");
            AddTranslation("Disembowel", "剖腹");
            AddTranslation("When [creature] is sacrificed, an amount of guts equal to its remaining health are created in its owners hand.", "[creature]见祀，则其主手中生脏，如其余命之数。");
            AddTranslation("[creature]s guts explode into your hands.", "[creature]之脏迸入汝手。");
            AddTranslation("Distraction", "诱替");
            AddTranslation("When [creature] would be struck, a distraction is left in its place and [creature] moves to the right.", "[creature]将受击，则留一诱物于故处，而自身右移。");
            AddTranslation("Diver", "潜者");
            AddTranslation("[creature] can strike the opposing card even while it is submerged.", "[creature]虽对位潜伏，亦可击之。");
            AddTranslation("The next card drawn while [creature] is alive and on the board will be duplicated.", "[creature]存于场，则后所引之牌将见复制。");
            AddTranslation("Divisibility Strike", "奇偶击");
            AddTranslation("At the end of each turn, [creature] will alternate between striking all odd indexed opponent slots, and all even indexed opponent slots.", "每合终，[creature]交替击敌侧诸奇列与诸偶列。");
            AddTranslation("Docile", "驯");
            AddTranslation("[creature] will wait a set number of turns in between being allowed to attack.", "[creature]每攻之间，须俟定数之合。");
            AddTranslation("Doomed", "定死");
            AddTranslation("At the end of the turn, [creature] will perish.", "合终，[creature]死。");
            AddTranslation("Double Tap", "并击");
            AddTranslation("When a friendly creature strikes an opponent creature, [creature] will also attack that opponent creature.", "友物攻敌物时，[creature]亦攻彼物。");
            AddTranslation("[creature] aids its comrades in battle!", "[creature]助其同袍战矣！");
            AddTranslation("Downdraft", "下风");
            AddTranslation("[creature] will grant the power of flight to creatures to it's left and right.", "[creature]授其左右之物以飞。");
            AddTranslation("Draw", "引");
            AddTranslation("When [creature] is played, its owner draws cards equal to the number inscribed on this sigil.", "[creature]既陈，其主引牌，如印所书之数。");
            AddTranslation("Dripping", "滴行");
            AddTranslation("At the end of the owner's turn, [creature] will move in the direction inscribed in the sigil and leave part of it's own body in it's wake.", "持牌者合终，[creature]循印所志而移，并遗其身之一分于行迹。");
            AddTranslation("Drop", "引即陈");
            AddTranslation("If[creature] is drawn as part of your opening hand, it will be automatically played on a random board space for free.", "若[creature]为开局手牌所引，则免费自陈于随机空位。");
            AddTranslation("When [creature] is played, you may search your deck for any card and create a duplicate of it in your hand.", "[creature]既陈，汝可于牌列索任一牌，并生其副本于手。");
            AddTranslation("Duppelgang", "双影");
            AddTranslation("When [creature] is played, draw copies of cards adjacent to it from your deck to your hand.", "[creature]既陈，自牌列引其邻牌之副本入手。");
            AddTranslation("Eager", "亟");
            AddTranslation("[creature] will gain +2 power for the duration of it's first turn on the board.", "[creature]在场之初合，威加2。");
            AddTranslation("Easy Pickings", "易取");
            AddTranslation("When [creature] is played, all other creatures on the board with 1 health will perish.", "[creature]既陈，场上一切命为1之物皆立死。");
            AddTranslation("Emancipation", "脱化");
            AddTranslation("When [creature] is played, copies of any bottled cards the owner possesses are created in the owner's hand.", "[creature]既陈，则其主持有之诸瓶牌，皆生副本于手。");
            AddTranslation("Emerald Core", "绿玉核");
            AddTranslation("When [creature] perishes, an Emerald Vessel is created in its place.", "[creature]死，则其处生一绿玉皿。");
            AddTranslation("Emerald Heart", "绿玉心");
            AddTranslation("When [creature] perishes, an Emerald Mox is created in its place.", "[creature]死，则其处生一绿玉玛珂。");
            AddTranslation("Enchanting", "赋印");
            AddTranslation("When [creature] is played, all creatures you control gain one of its other sigils, at random.", "[creature]既陈，则汝所御诸物随机得其一他印。");
            AddTranslation("Endangered", "垂危");
            AddTranslation("At the end of the turn, [creature] has a one in four chance to perish.", "合终，[creature]有四分之一之几而死。");
            AddTranslation("Enemy Lines", "敌阵");
            AddTranslation("When [creature] attacks, it will target all opponent slots that it is NOT directly opposing.", "[creature]攻时，凡非其正对之敌位，皆为所向。");
            AddTranslation("Energy Dependent", "恃能");
            AddTranslation("If the user has 0 Energy, [creature] will perish.", "若其主之能为0，[creature]死。");
            AddTranslation("Enraged", "愤");
            AddTranslation("When [creature] is struck, it gains 1 attack power.", "[creature]受击，则威加1。");
            AddTranslation("Entangle", "缠");
            AddTranslation("When [creature] perishes, its killer has their power reduced by half and rounded down for one turn.", "[creature]死，则杀之者威半减，取下而止于一合。");
            AddTranslation("Erratic", "无恒");
            AddTranslation("At the end of the owner's turn, [creature] will move in the direction inscribed on the sigil. It will not move if the target slot is obstructed. Direction has a 50/50 chance to change after moving.", "持牌者合终，[creature]循印所志而移。若前格有阻，则不移；每移之后，有半几改其向。");
            AddTranslation("Esprit De Corps", "同心");
            AddTranslation("While [creature] is on the board, creatures in the leftmost and rightmost slots on the same side of the board gain 1 power.", "[creature]在场，则同侧最左与最右之物威加1。");
            AddTranslation("While[creature] is alive and on the board, its owner may not take fatal damage.", "[creature]存于场，则其主不受致死之伤。");
            AddTranslation("Even Strike", "偶列击");
            AddTranslation("[creature] will strike all opposing spaces in even indexed columns when it attacks. Column index is counted from the left, starting at 1.", "[creature]攻时，凡敌侧偶列之位皆击之。列数自左计，始于1。");
            AddTranslation("Exceptional Sacrifice", "奇祭");
            AddTranslation("[creature] counts as 6 Blood rather than 1 Blood when sacrificed. Does not pair well with many lives.", "[creature]见祀时，算6血，非1血。与多命不甚相宜。");
            AddTranslation("Bloodstarved Beast", "嗜血兽");
            AddTranslation("When [creature] is played, it's owner may search their graveyard for a card, and add that card to their hand.", "[creature]既陈，其主可于墓地索一牌而纳之手。");
            AddTranslation("Exploding Corpse", "尸爆");
            AddTranslation("When [creature] perishes, all empty spaces on the board are filled with it's innards.", "[creature]死，则场上诸空位皆以其脏充之。");
            AddTranslation("Expulsion", "吐逐");
            AddTranslation("When [creature] takes damage, it regurgitates it's contents into the adjacent space to the right.", "[creature]受伤，则吐其所吞于右邻之位。");
            AddTranslation("Exsanguination", "渫血");
            AddTranslation("While [creature] is on the board, friendly creatures have their blood cost reduced by 1.", "[creature]在场，则友物之血费减1。");
            AddTranslation("Eye For Battle", "战目");
            AddTranslation("[creature] will lose all attack power if it is not directly opposing an opponent's creature.", "[creature]不正对敌物，则尽失其威。");
            AddTranslation("Face To Face", "相对");
            AddTranslation("When [creature] is drawn, it morphs to mimic the current opponent.", "[creature]既引，则化而效今敌。");
            AddTranslation("Fan Tailed", "扇尾");
            AddTranslation("When [creature] is played, all friendly creatures on the board take flight.", "[creature]既陈，场上诸友物皆得飞。");
            AddTranslation("Fatal Flank", "致翼");
            AddTranslation("When [creature] perishes to combat, it creates a specific creature in all empty adjacent slots.", "[creature]战死，则诸相邻空位皆生一定之物。");
            AddTranslation("Fearsome", "可畏");
            AddTranslation("When [creature] targets a slot occupied by another creature, that creature will move to make way for it if there is room to do so.", "[creature]所向之位若为他物所据，则其物有隙可徙，便徙以让。");
            AddTranslation("File Explorer", "探卷");
            AddTranslation("When [creature] is played, choose two creatures from random selection of your deck. These creatures will define this cards power and health at random. If this card dies, the creatures used to define its stats perish as well.", "[creature]既陈，自牌列随机择二物。此二物将随机定此牌之威与命。若此牌死，则定其属性之物亦并死。");
            AddTranslation("Filter Feeder", "滤食");
            AddTranslation("When a creature perishes adjacent to [creature], the card will gain either 1 power or 1 health.", "邻[creature]之物死，则此牌或加1威，或加1命。");
            AddTranslation("Firebomb", "火爆");
            AddTranslation("When [creature] perishes, creatures adjacent to it and opposing it take 2 damage and gain the Burning sigil.", "[creature]死，则邻之与正对之物受2伤，并得燃印。");
            AddTranslation("[creature] explodes, spraying fire everywhere!", "[creature]爆矣，火四溅焉！");
            AddTranslation("Fire In The Hole", "穴中火");
            AddTranslation("When [creature] perishes, it's owner may choose an opponent slot. The creature in that slot will take ten damage.", "[creature]死，则其主可择敌之一位；其位之物受10伤。");
            AddTranslation("Fire Resistant", "耐火");
            AddTranslation("[creature] will not take damage from the Burning sigil.", "[creature]不受燃印之伤。");
            AddTranslation("Flank Blast", "侧爆");
            AddTranslation("When [creature] dies, adjacent friendly creatures are dealt 10 damage.", "[creature]死，则相邻友物受10伤。");
            AddTranslation("Flea Ridden", "多蚤");
            AddTranslation("When [creature] perishes to combat, it creates a Flea in all empty adjacent slots. A Flea is defined as 0 Power, 1 Health, Eager, Frail", "[creature]战死，则诸相邻空位皆生跳蚤。跳蚤者：0威、1命，亟、脆。");
            AddTranslation("Flighty", "轻扬");
            AddTranslation("At the end of the turn, [creature] will move to a random available space.", "合终，[creature]随机移于一可用之位。");
            AddTranslation("Fossil Record", "化石录");
            AddTranslation("While [creature] is on the board, terrain cards will award 3 additional bones when destroyed.", "[creature]在场，则地形牌毁时，额外授3骨。");
            AddTranslation("Frail", "脆");
            AddTranslation("When [creature] is struck, it will perish.", "[creature]受击，则立死。");
            AddTranslation("Frail Sacrifice", "脆祀");
            AddTranslation("When [creature] is sacrificed, the creature it was sacrificed for gains the Frail Sigil.", "[creature]见祀，则受其祀之物得脆印。");
            AddTranslation("Freefall", "坠");
            AddTranslation("While [creature] is on the board, all airborne creatures require exactly 1 less of their respective cost to be played.", "[creature]在场，则诸飞物所需之费，各减1。");
            AddTranslation("Friend Finder", "求友");
            AddTranslation("When [creature] is played, a random friend is created in the slots to it's left and right.", "[creature]既陈，其左右空位各生一随机之友。");
            AddTranslation("Fringe Strike", "边击");
            AddTranslation("[creature] will always attack the leftmost and rightmost opponent lanes.", "[creature]恒击敌侧最左与最右之路。");
            AddTranslation("Frog Friend", "蛙友");
            AddTranslation("At the end of the owner's turn, [creature] will move in the direction inscrybed in the sigil. You may search your deck for any 'frog' or 'toad' creatures, and play them in [creature]'s old space.", "持牌者合终，[creature]循印所志而移。汝可于牌列索诸“蛙”或“蟾”之物，而陈之于[creature]故处。");
            AddTranslation("Emerald Dependant", "恃绿玉");
            AddTranslation("If [creature]'s owner controls no green mox gems, it will perish.", "若[creature]之主持无绿玉玛珂，则死。");
            AddTranslation("[creature] requires an emerald mox to exist and perishes.", "[creature]恃绿玉玛珂而存；无则死。");
            AddTranslation("Ruby Dependant", "恃红玉");
            AddTranslation("If [creature]'s owner controls no orange mox gems, it will perish.", "若[creature]之主持无红玉玛珂，则死。");
            AddTranslation("[creature] requires a ruby mox to exist and perishes.", "[creature]恃红玉玛珂而存；无则死。");
            AddTranslation("Sapphire Dependant", "恃蓝玉");
            AddTranslation("If [creature]'s owner controls no blue mox gems, it will perish.", "若[creature]之主持无蓝玉玛珂，则死。");
            AddTranslation("[creature] requires a sapphire mox to exist and perishes.", "[creature]恃蓝玉玛珂而存；无则死。");
            AddTranslation("Gem Shedder", "遗玉");
            AddTranslation("At the end of the owner's turn, [creature] will move in the direction inscrybed in the sigil and drop a random Gem in its old place.", "持牌者合终，[creature]循印所志而移，并于故处随机遗一玉。");
            AddTranslation("Gem Skeptic", "疑玉");
            AddTranslation("While [creature] is on the board, its owner may not play any mox gems.", "[creature]在场，则其主不得陈任何玛珂。");
            AddTranslation("Giant", "巨");
            AddTranslation("While [creature] is on the board, any strikes against its owner will target it instead.", "[creature]在场，则凡攻其主者，皆转而向之。");
            AddTranslation("Gift Bearer", "怀礼");
            AddTranslation("When [creature] perishes, a random creature is created in your hand.", "[creature]死，则于汝手生一随机之物。");
            AddTranslation("Glitterheart", "辉心");
            AddTranslation("While [creature] is on the board, playing a mox gem will increase its health by 1.", "[creature]在场，则陈玛珂可使其命加1。");
            AddTranslation("[creature] is bolstered by the played gem.", "[creature]因所陈之玉而益。");
            AddTranslation("Globetrotter", "周行");
            AddTranslation("At the end of the owner's turn,[creature] will move in the direction inscribed on the sigil. If obstructed, it will move to the other side of the board and begin to circle back.", "持牌者合终，[creature]循印所志而移。若有阻，则绕至牌局彼侧而旋返。");
            AddTranslation("When [creature] is played, a Black Goat is created in its owners hand.", "[creature]既陈，其主手中生一黑山羊。");
            AddTranslation("Gold Digger", "掘金");
            AddTranslation("At the end of the owner's turn, [creature] will generate 1 currency, up to five times per battle.", "持牌者合终，[creature]生1金，每战至多五次。");
            AddTranslation("Gold Rush", "金潮");
            AddTranslation("When [creature] is played, all opponent cards on the board perish, and are replaced by Gold Nuggets.", "[creature]既陈，敌牌尽死，而皆为金块所代。");
            AddTranslation("Gooey", "黏");
            AddTranslation("When [creature] is struck, the striker loses 1 power.", "[creature]受击，则击者失1威。");
            AddTranslation("Scrape that gunk off the hull, lads! Full steam ahead!", "刮去船壳之黏胶，诸子！鼓汽疾进！");
            AddTranslation("No amount of ooze can slow the motion of a celestial body...", "黏胶虽多，不能缓天体之行……");
            AddTranslation("Graveyard Shift", "冢更");
            AddTranslation("When [creature] perishes by combat, it leaves something else in it's old space. Unlike Frozen Away, this new creature will retain the sigils and buffs of the original.", "[creature]战死，则其故处留一他物。异于“冰封禁锢”，新物犹存故物之印与益。");
            AddTranslation("Gravity", "引");
            AddTranslation("When [creature] is played, it's owner may choose any opponent creature, and move it to any open space on their side of the board.", "[creature]既陈，其主可择任一敌物，移之于己侧任一空位。");
            AddTranslation("Green Inspiration", "绿感");
            AddTranslation("While [creature] is on the board, all friendly creatures which cost a green gem gain +2 health.", "[creature]在场，则凡费绿玉之友物，命加2。");
            AddTranslation("Gut Spewer", "吐脏者");
        }
    }
}
