using DiskCardGame;

namespace ClassicChineseLanguagePack
{
    internal static class InscryptionModsBatch28
    {
        private static void AddTranslation(string english, string classical)
        {
            ClassicChineseLanguagePackPlugin.Translate(
                ClassicChineseLanguagePackPlugin.GUID, null, english, classical, Language.ChineseSimplified);
        }

        public static void RegisterTranslations()
        {
            // AllTheSigilsMod (part 2)
            AddTranslation("Gut Spewer", "腑涌");
            AddTranslation("When [creature] is played, its innards are created in your hand.", "当[creature]陈，则其内腑生于汝手。");
            AddTranslation("Harbinger", "先兆");
            AddTranslation("When a friendly creatures perishes, [creature] will move to fill it's empty space.", "友物亡，则[creature]移而补其虚位。");
            AddTranslation("Harts Within", "蹄藏");
            AddTranslation("When [creature] is struck, a random creature from the hooved tribe is created in your hand.", "当[creature]受击，则蹄族随机一物生于汝手。");
            AddTranslation("Haunter", "鬼缠");
            AddTranslation("When [creature] dies to combat, it haunts the space it died in. Creatures that enter this space absorb its old sigils.", "当[creature]因斗而亡，则魍于其死位。入此位之物，尽受其旧印。");
            AddTranslation("[creature] leaves its sigils behind in the ethereal plane!", "[creature]遗其诸印于幽界！");
            AddTranslation("At the end of the owner's turn, [creature]s owner may choose a creature they control. That creature gains 1 health.", "于其主合末，其主可择一己物，使之命+1。");
            AddTranslation("Healshield", "愈盾");
            AddTranslation("If [creature] does not take damage during a turn, it will gain Armor at the start of its owner's next turn.", "若[creature]一合不受伤，则于其主下合始得坚甲。");
            AddTranslation("Herald", "宣告");
            AddTranslation("When[creature] attacks an opposing creature and it perishes, creatures to the left and right of this card gain 1 power.", "当[creature]击敌物而令其亡，则此牌左右之物各+1威。");
            AddTranslation("High Powered", "强耗");
            AddTranslation("At the start of its owners turn, [creature] will consume 1 energy.", "于其主合始，[creature]耗1能。");
            AddTranslation("Home Run", "定路");
            AddTranslation("[creature] will remember the lane in which it was played, and will always attack that lane.", "[creature]记其所陈之路，恒击其路。");
            AddTranslation("Hook Line And Sinker", "钩沉");
            AddTranslation("When [creature] perishes by combat, the opposing creature will be pulled into it's old space.", "当[creature]因斗而亡，则敌物被拽入其故位。");
            AddTranslation("Hypermorphic", "异化");
            AddTranslation("At the end of each turn, [creature] will transform into a random card of the same type and quality.", "每合末，[creature]化为同类同品之随机牌。");
            AddTranslation("Ignition", "燃印");
            AddTranslation("When [creature] strikes a creature, that creature gains the Burning sigil.", "当[creature]击物，则彼得燃印。");
            AddTranslation("Immaculate Form", "净形");
            AddTranslation("While [creature] is on the board, the gems cost of all friendly creatures is reduced by 2 gems.", "当[creature]在场，诸友物之玛珂费皆减2。");
            AddTranslation("Immaterial", "虚体");
            AddTranslation("Any attacks made against [creature] during the opponents turn will pass straight through, and hit the creature's owner directly.", "敌合中凡击[creature]者，皆穿而直中其主。");
            AddTranslation("Immortal Coil", "不灭环");
            AddTranslation("While [creature] is alive on the board, any friendly creatures that die to combat will return to the owner's hand, though slightly weakened.", "当[creature]在场而生，友物因斗而亡者，皆返其主手，惟稍衰。");
            AddTranslation("Incontinent", "失禁");
            AddTranslation("When [creature] would be struck, a mess is created in its place and a card bearing this sigil moves to the right.", "当[creature]将受击，则其位生秽，带此印之牌右移。");
            AddTranslation("Inspiring Sacrifice", "励祀");
            AddTranslation("When [creature] is sacrificed, it grants its sigils to the creature it was sacrificed for.", "当[creature]为祀，则以诸印授于所祀之物。");
            AddTranslation("Instant Effect", "立效");
            AddTranslation("After resolving on the board, [creature] will immediately perish.", "在场结算毕，[creature]立亡。");
            AddTranslation("Killing Joke", "杀戏");
            AddTranslation("While [creature] is on the board, all friendly creatures which cost an orange gem will either gain +1 power or -1 power when played.", "当[creature]在场，凡费橙玛珂之友物，陈时或+1威，或-1威。");
            AddTranslation("[creature] randomly modifies the power of the Orange Gem cost card!", "[creature]随机改橙玛珂费牌之威！");
            AddTranslation("Kin Bearer", "同承");
            AddTranslation("When [creature] perishes, a random creature of the same tribe is created in your hand.", "当[creature]亡，则同族随机一物生于汝手。");
            AddTranslation("Kindred", "同族");
            AddTranslation("When [creature] is played, random common creatures of the same tribe will be played for free to its left and right.", "当[creature]陈，则其左右随机免费陈同族常物。");
            AddTranslation("L33p Leaver", "跃离");
            AddTranslation("At the end of the owner's turn,[creature] will move in the direction inscrybed in the sigil and drop a L33pB0t in its old place.", "于其主合末，[creature]依印所书之向而移，并于故位坠L33pB0t。");
            AddTranslation("Landscaper", "平地");
            AddTranslation("When[creature] is played, any terrain cards on the board are removed and added to it's owner's hand.", "当[creature]陈，则场上诸地形牌尽除，归其主手。");
            AddTranslation("Lash Out", "反击");
            AddTranslation("At the end of the owner's turn,[creature] will attack a random opposing slot.", "于其主合末，[creature]随机击敌一位。");
            AddTranslation("Airborne Latch", "翔缀");
            AddTranslation("When [creature] perishes, its owner chooses a creature to gain the airborne sigil.", "当[creature]亡，其主择一物，使得翔袭印。");
            AddTranslation("Annoying Latch", "烦缀");
            AddTranslation("When [creature] perishes, its owner chooses a creature to gain the annoying sigil.", "当[creature]亡，其主择一物，使得烦印。");
            AddTranslation("Burning Latch", "燃缀");
            AddTranslation("When [creature] perishes, its owner chooses a creature to gain the burning sigil.", "当[creature]亡，其主择一物，使得燃印。");
            AddTranslation("Burrower Latch", "穴缀");
            AddTranslation("When [creature] perishes, its owner chooses a creature to gain the burrower sigil.", "当[creature]亡，其主择一物，使得穴印。");
            AddTranslation("Frail Latch", "脆缀");
            AddTranslation("When [creature] perishes, its owner chooses a creature to gain the frail sigil.", "当[creature]亡，其主择一物，使得脆印。");
            AddTranslation("Temporarily Gemified", "暂珂化");
            AddTranslation("[creature] has been temporarily gemified until the end of battle.", "[creature]暂珂化，至战终。");
            AddTranslation("Gem Latch", "珂缀");
            AddTranslation("When[creature] perishes, its owner chooses a creature to become gemified.", "当[creature]亡，其主择一物，使之珂化。");
            AddTranslation("Haunter Latch", "鬼缀");
            AddTranslation("When [creature] perishes, its owner chooses a creature to gain the haunter sigil.", "当[creature]亡，其主择一物，使得鬼缠印。");
            AddTranslation("Null Latch", "虚缀");
            AddTranslation("When [creature] perishes, its owner chooses a creature to gain the null conduit sigil.", "当[creature]亡，其主择一物，使得虚渠印。");
            AddTranslation("Overclocked Latch", "超速缀");
            AddTranslation("When [creature] perishes, its owner chooses a creature to gain 1 power, and the overclocked sigil.", "当[creature]亡，其主择一物，使之+1威，并得超速印。");
            AddTranslation("Sniper Latch", "狙缀");
            AddTranslation("When [creature] perishes, its owner chooses a creature to gain the sniper sigil.", "当[creature]亡，其主择一物，使得狙印。");
            AddTranslation("Sprinter Latch", "疾缀");
            AddTranslation("When [creature] perishes, its owner chooses a creature to gain the sprinter sigil.", "当[creature]亡，其主择一物，使得疾驰印。");
            AddTranslation("Stalwart Latch", "坚缀");
            AddTranslation("When [creature] perishes, its owner chooses a creature to gain the stalwart sigil.", "当[creature]亡，其主择一物，使得坚毅印。");
            AddTranslation("Totem Latch", "偶缀");
            AddTranslation("When [creature] perishes, its owner chooses a creature to gain the sigil on their current totem.", "当[creature]亡，其主择一物，使得其今神偶之印。");
            AddTranslation("Waterborne Latch", "潜缀");
            AddTranslation("When [creature] perishes, its owner chooses a creature to gain the waterborne sigil.", "当[creature]亡，其主择一物，使得潜袭印。");
            AddTranslation("Leaper", "跃者");
            AddTranslation("At the end of the owner's turn, [creature] will move in the direction inscribed in the sigil, leaping over single card obstructions.", "于其主合末，[creature]依印所书之向而移，越一牌之障。");
            AddTranslation("When [creature] is struck, it creates a number of cards in the owner's hand equal to it's remaining HP, then perishes.", "当[creature]受击，则以余命数，生等量牌于主手，而后亡。");
            AddTranslation("Lockdown", "锁缚");
            AddTranslation("When [creature] is played, the opposing creature loses attack power equal to the power of this card and gains the Stalwart sigil.", "当[creature]陈，则敌物失等同于此牌之威，并得坚毅印。");
            AddTranslation("[creature] locks the opposing creature in place!", "[creature]锁敌物于位！");
            AddTranslation("Lonesome", "孤");
            AddTranslation("[creature] gains +1 power for each adjacent empty space.", "每邻一空位，[creature]得+1威。");
            AddTranslation("Lurk", "潜伏");
            AddTranslation("Submerges during the opponent's turn. When a creature moves into the space opposing [creature], they are dealt 1 damage.", "敌合时潜没。若有物移入其对位，则受1伤。");
            AddTranslation("Magitech", "魔工");
            AddTranslation("While [creature] is alive and on the board, playing a mox gem will provide it's owner with an energy cell.", "当[creature]在场而生，陈一玛珂，则其主得1能。");
            AddTranslation("[creature] channels electrical power through your gems!", "[creature]以电通诸玛珂！");
            AddTranslation("Malware", "恶码");
            AddTranslation("You may not play [creature] unless you are three or less damage away from losing the game.", "非距败三伤内，不得陈[creature]。");
            AddTranslation("Marcescent", "枯荣");
            AddTranslation("When [creature] attacks an opposing creature and it perishes, this card gains it's attack power.", "当[creature]击敌物而令其亡，则此牌得其威。");
            AddTranslation("Mason", "砌匠");
            AddTranslation("When [creature] is played, a random obelisk is created in your hand.", "当[creature]陈，则随机一方碑生于汝手。");
            AddTranslation("Mauler", "猛击");
            AddTranslation("[creature] will deal overkill damage directly to the opponent.", "[creature]之溢伤直加于敌。");
            AddTranslation("Medicinal", "愈疗");
            AddTranslation("When [creature] is played, it heals all friendly creatures by 2 and removes all negative sigils from friendly creatures.", "当[creature]陈，则诸友物皆愈二命，并除其负印。");
            AddTranslation("Mirrific", "镜化");
            AddTranslation("When [creature] perishes, it's owner chooses a creature to gain the Mirror rorriM ability.", "当[creature]亡，其主择一物，使得镜返能。");
            AddTranslation("Mockery", "讥拟");
            AddTranslation("If [creature] is played opposite an opponent's creature, it's stats change to mimic that creature's stats.", "若[creature]陈于敌物对位，则其威命拟彼。");
            AddTranslation("Morph Mover", "变移");
            AddTranslation("When [creature] is drawn, this sigil is replaced by a random movement related sigil.", "当[creature]被引，则此印换为随机移印。");
            AddTranslation("Motivator", "励威");
            AddTranslation("When [creature] strikes a creature, that creature gains 1 power.", "当[creature]击物，则彼得+1威。");
            AddTranslation("Moxcraft", "珂造");
            AddTranslation("When [creature] is struck, a random mox is created in your hand.", "当[creature]受击，则随机一玛珂生于汝手。");
            AddTranslation("Mox Max", "珂极");
            AddTranslation("[creature] cannot be played unless two cards which grant its respective mox cost colour are present on the owners side of the board.", "除非其主场侧有二牌供其费色，不得陈[creature]。");
            AddTranslation("Moxwarp", "珂跃");
            AddTranslation("While [creature] is alive on the board, any enemy attack that enters a sapphire mox will be returned out of all ruby mox, and vice versa.", "当[creature]在场而生，凡敌击入蓝玛珂者，皆自诸赤玛珂返出；反之亦然。");
            AddTranslation("Mystery Mox", "秘珂");
            AddTranslation("When [creature] is drawn, this sigil is replaced by a random gem-granting sigil.", "当[creature]被引，则此印换为随机赐珂印。");
            AddTranslation("Nature Of The Beast", "兽性");
            AddTranslation("When [creature] perishes, a completely random creature is created in the owner's hand.", "当[creature]亡，则完全随机一物生于主手。");
            AddTranslation("Obedient", "顺从");
            AddTranslation("At the end of the owner's turn, [creature] will move to an empty space on the same side of the board, chosen by it's owner.", "于持牌人合终，[creature]移至场同侧一空位，由其主择之。");
            AddTranslation("Odd Strike", "奇列击");
            AddTranslation("[creature] will strike all opposing spaces in odd indexed columns when it attacks. Column index is counted from the left, starting at 1.", "列序自左起，始于1；[creature]击时，凡奇数列敌位尽击。");
            AddTranslation("Omni Guardian", "全卫");
            AddTranslation("When [creature] is played, all friendly creatures on the board gain armour.", "[creature]陈时，场上友物尽得坚甲。");
            AddTranslation("[creature] gives the Armored sigil to all friendly creatures.", "[creature]授友物以坚甲印。");
            AddTranslation("Crusher", "碎击");
            AddTranslation("[creature] will gain 2 power when opposed by a terrain card.", "[creature]为地形牌对位时，得2威。");
            AddTranslation("Deerly Departed", "鹿逝");
            AddTranslation("[creature] will gain 2 power when opposed by a creature of the Hooved tribe.", "[creature]为蹄族之物对位时，得2威。");
            AddTranslation("Dog Gone", "犬逝");
            AddTranslation("[creature] will gain 2 power when opposed by a creature of the Canine tribe.", "[creature]为犬族之物对位时，得2威。");
            AddTranslation("Fowl Play", "禽戏");
            AddTranslation("[creature] will gain 2 power when opposed by a creature of the Avian tribe.", "[creature]为鸟族之物对位时，得2威。");
            AddTranslation("Insectivore", "食虫");
            AddTranslation("[creature] will gain 2 power when opposed by a creature of the Insect tribe.", "[creature]为虫族之物对位时，得2威。");
            AddTranslation("Snakebite", "蛇噬");
            AddTranslation("[creature] will gain 2 power when opposed by a creature of the Reptile tribe.", "[creature]为爬族之物对位时，得2威。");
            AddTranslation("Orange Inspiration", "橙启");
            AddTranslation("While[creature] is on the board, all friendly cards which cost an orange gem gain +1 power.", "[creature]在场时，凡费橙玛珂之友牌，皆+1威。");
            AddTranslation("Organ Thief", "夺脏");
            AddTranslation("When [creature] kills another creature, it's remains are created in your hand.", "[creature]杀他物时，其遗骸生于汝手。");
            AddTranslation("Osteoklepty", "盗骨");
            AddTranslation("When [creature] is played, it steals all of the opponents bones for it's owner.", "[creature]陈时，尽盗敌骨归其主。");
            AddTranslation("Other Side", "彼岸");
            AddTranslation("While [creature] is on the board, any friendly creatures that die in combat will be returned to the owner's hand as skeletons.", "[creature]在场时，凡友物战死者，皆化骷髅还主手。");
            AddTranslation("Painful Presence", "痛临");
            AddTranslation("On upkeep, all creatures adjacent to [creature] vertically, horizontally, or diagonally take 1 damage.", "维持时，凡与[creature]上下左右及斜邻之物，皆受1伤。");
            AddTranslation("Paralytic", "痹击");
            AddTranslation("When [creature] strikes a creature, that creature loses 1 power.", "[creature]击物时，其失1威。");
            AddTranslation("Parthenogenesis", "孤生");
            AddTranslation("When [creature] dies to combat, a larval form is left in it's old space that evolves into an exact clone after 1 turn.", "[creature]战死时，故位留幼形，经一合化与其全同之形。");
            AddTranslation("Perfect Form", "完形");
            AddTranslation("While [creature] is on the board, the gems cost of all friendly creatures is reduced by 1 gem.", "[creature]在场时，凡友物之玛珂费皆减1。");
            AddTranslation("Phantasmic", "幻步");
            AddTranslation("At the end of the turn, [creature] will move in the direction inscribed in the sigil, phasing past obstacles and wrapping around to the other side of the board if movement is impossible.", "合终，[creature]循印所书之向而行，穿障无碍；若不可行，则绕至场彼侧。");
            AddTranslation("Piercing", "穿刺");
            AddTranslation("When [creature] strikes a slot which has a creature queued behind it, the queued creature will take 1 damage.", "[creature]击一位而其后有待行之物，则后物受1伤。");
            AddTranslation("Pinnacle Strike", "巅击");
            AddTranslation("[creature] will strike all opponent spaces when it attacks.", "[creature]击时，敌位尽击。");
            AddTranslation("Point Nemo", "寂点");
            AddTranslation("When [creature] is played, all creatures on the board gain the Waterborne sigil.", "[creature]陈时，场上众物皆得潜袭印。");
            AddTranslation("Potent", "强赐");
            AddTranslation("When [creature] is sacrificed, the creature it was sacrificed for gains a random sigil.", "[creature]为祀时，其所祀之物得一随机印。");
            AddTranslation("Preemptive Strike", "先击");
            AddTranslation("[creature] will attack once when first played.", "[creature]初陈时，先击一次。");
            AddTranslation("[creature] makes a free attack!", "[creature]白击一次！");
            AddTranslation("Propagation", "繁衍");
            AddTranslation("When [creature] attacks an opposing creature and it perishes, a creature is created on the board to the left or right of this card.", "[creature]击敌物而其亡时，于此牌左右之一位生一物。");
            AddTranslation("Prophecy", "预兆");
            AddTranslation("When [creature] is played, you may look at three cards from your deck and choose them in order. The next three cards you draw will be the cards you were shown, in the order that you chose them.", "[creature]陈时，汝可观牌列三牌，并依序择之。汝后引三牌，即所示之牌，且循汝所择之序。");
            AddTranslation("I will allow you to choose from three cards. These three cards will be the next three cards you draw from your deck, in the order you choose them here.", "余许汝自三牌中择之。此三牌即汝后引之三牌，循汝今所择之序。");
            AddTranslation("Choose three creatures, and alter your next draws.", "择三物，以易汝后引。");
            AddTranslation("You know how this goes.", "汝知其例。");
            AddTranslation("Choose from three cards. These three cards will be the next three cards you draw from your deck, in the order you chose them.", "自三牌中择之。此三牌即汝后引之三牌，循汝所择之序。");
            AddTranslation("Choose your next three draws.", "择汝后三引。");
            AddTranslation("Hmmm... your new prophecy overwrites the old, it would seem.", "嗯……汝新预兆似覆旧者。");
            AddTranslation("Your new prophecy overwrites the old!", "汝新预兆覆旧矣！");
            AddTranslation("Hmm... very well", "嗯……善。");
            AddTranslation("You do not have enough cards left for a prophecy.", "汝余牌不足以成预兆。");
            AddTranslation("You don't have enough cards left to make a new prophecy!", "汝余牌不足以立新预兆！");
            AddTranslation("Pure Heart", "纯心");
            AddTranslation("When [creature] perishes, a Pinnacle Mox is created in its place.", "[creature]亡时，其位生巅玛珂。");
            AddTranslation("Pushover", "易推");
            AddTranslation("If [creature] is opposed by an enemy creature, the card will perish.", "若[creature]为敌物对位，则此牌亡。");
            AddTranslation("Put Sentry Here", "置哨");
            AddTranslation("When [creature] is played, a Sentry Drone is created to its left and right.", "[creature]陈时，其左右各生一哨机。");
            AddTranslation("Quad Strike", "四击");
            AddTranslation("[creature] will strike each opposing space to the left and right of the spaces across from it as well as striking the space in front of it an additional time.", "[creature]击时，其对位左右之敌位尽击，并正前之位复击一次。");
            AddTranslation("Quickdraw", "速陈");
            AddTranslation("[creature] will automatically play itself from your deck onto a random space at the start of each battle.", "每战始，[creature]自牌列自动陈于一随机位。");
            AddTranslation("Ranger", "游猎");
            AddTranslation("When [creature] is played, it's owner may choose an opponent creature. That creature will take 10 damage.", "[creature]陈时，其主可择一敌物，使受10伤。");
            AddTranslation("Ravenous", "饕击");
            AddTranslation("When [creature] kills a creature, it will gain an additional strike against the opposing space until the end of combat.", "[creature]杀物后，于战终前，其对位多击一次。");
            AddTranslation("Recharge", "再充");
            AddTranslation("When [creature] is played, it's owner regains 1 energy. Does not affect the current energy maximum.", "[creature]陈时，其主复1能，然不增今能上限。");
            AddTranslation("Recycle", "回收");
            AddTranslation("While [creature] is on the board, when any friendly creature perishes by combat a special card will be created in the owners hand. The card created depends on the temple of the friendly card which perishesd.", "[creature]在场时，凡友物因战而亡，持牌人手中生一特牌。所生之牌，视其亡牌之殿而定。");
            AddTranslation("Reflective", "反照");
            AddTranslation("When [creature] is opposed by a creature, it gains power equal to the opposing creatures power.", "[creature]为物对位时，得与敌物之威等之威。");
            AddTranslation("Regenerator", "再生");
            AddTranslation("At the start of the owners turn, [creature] will heal 1 health.", "于持牌人合初，[creature]愈1命。");
            AddTranslation("[creature] regenerates one health!", "[creature]复一命！");
            AddTranslation("Rememberance", "追忆");
            AddTranslation("When [creature] is played, it's owner may search their graveyard for a card. This sigil is replaced by that cards sigils.", "[creature]陈时，其主可于墓地索一牌。此印改为彼牌诸印。");
            AddTranslation("Remote Controlled", "遥控");
            AddTranslation("When [creature] is played, a Remote Controller is created in the owner's hand. When the remote controller is struck, [creature] will attack the striker.", "[creature]陈时，持牌人手中生一遥控器。遥控器受击，则[creature]击其击者。");
            AddTranslation("Reroute", "转移");
            AddTranslation("At the end of the turn, [creature] will swap places with a random creature on the same side of the board.", "合终，[creature]与场同侧一随机物互换其位。");
            AddTranslation("Resilient", "韧体");
            AddTranslation("All damage taken by [creature] is reduced to 1.", "[creature]所受诸伤，皆减为1。");
            AddTranslation("Retreat", "退避");
            AddTranslation("When [creature] is struck, it will move to a random empty space on the same side of the board.", "[creature]受击时，移至场同侧一随机空位。");
            AddTranslation("Return Strike", "返击");
            AddTranslation("When [creature] is struck, it attacks in retaliation.", "[creature]受击时，反击。");
            AddTranslation("Revolve", "轮转");
            AddTranslation("When [creature] is played, all cards on the board are moved one space clockwise.", "[creature]陈时，场上诸牌皆顺时针移一位。");
            AddTranslation("Ripper", "裂噬");
            AddTranslation("[creature] will move to and destroy any free, 1 health, non-terrain creatures played, and becomes stronger for each one consumed.", "[creature]将移而灭凡无主、1命、非地形之陈物；每噬一物，则更强。");
            AddTranslation("Rock Eater", "食石");
            AddTranslation("When a Terrain card is played on the same side of the board as [creature], it will be consumed, granting it's stats and sigils to the card.", "当与[creature]同侧陈地形牌时，彼即为其所噬，而以其威命及诸印授此牌。");
            AddTranslation("Ruby Core", "赤核");
            AddTranslation("When [creature] perishes, a Ruby Vessel is created in its place.", "[creature]亡时，其位生赤皿。");
            AddTranslation("Running Strike", "奔击");
            AddTranslation("After attacking, [creature] will move in the direction inscribed on the sigil, striking the space opposing it's destination as it does so.", "击后，[creature]循印所书之向而移，并于其所至之对位击之。");
            AddTranslation("Rupture", "裂伤");
            AddTranslation("When [creature] deals damage to a creature, half of that damage, rounded down, is also dealt to that creature's owner.", "[creature]伤物时，其伤之半，取下整，亦加于其主。");
            AddTranslation("Sanguine", "血勇");
            AddTranslation("When a creature is sacrificed, [creature] gains 1 power until the end of combat.", "有物被祀时，[creature]得1威，至战终。");
            AddTranslation("Sapphire Core", "青核");
            AddTranslation("When [creature] perishes, a Sapphire Vessel is created in its place.", "[creature]亡时，其位生青皿。");
            AddTranslation("Sapphire Heart", "青心");
            AddTranslation("When [creature] perishes, a Sapphire Mox is created in its place.", "[creature]亡时，其位生青玛珂。");
            AddTranslation("Savage Ritual", "野祀");
            AddTranslation("When [creature] is sacrificed, it attacks once before dying.", "[creature]为祀时，先击一次而后死。");
            AddTranslation("Sentriple", "三哨");
            AddTranslation("When a creature moves into the space opposing [creature], they, as well as any creatures to their left or right, are dealt 1 damage.", "有物移入[creature]对位时，彼及其左右诸物皆受1伤。");
            AddTranslation("Sharp Bones", "锐骨");
            AddTranslation("When [creature] is struck, the striker is dealt damage equal to half the number of bones its owner has, rounded down.", "[creature]受击时，其击者受伤，数等其主所持骨之半，取下整。");
            AddTranslation("Sharper Quills", "锐翎");
            AddTranslation("When [creature] is struck, the striker is dealt 2 damage.", "[creature]被击，则击者受二伤。");
            AddTranslation("Sharpest Quills", "绝锋翎");
            AddTranslation("When [creature] is struck, the striker is dealt 3 damage.", "[creature]被击，则击者受三伤。");
            AddTranslation("Sharp Shot", "绝击");
            AddTranslation("When [creature] perishes, it gains +2 power and attacks once before dying.", "[creature]亡，则得+2威，先击一回而后亡。");
            AddTranslation("Sigil Mimic", "印仿");
            AddTranslation("If [creature] is played opposite an opponent's creature, this sigil is replaced by copies of that creatures sigils.", "[creature]若陈于敌物对位，则此印化为彼物诸印之副本。");
            AddTranslation("[creature] will also strike the slot to the left of the opposing slot when it attacks.", "[creature]击时，亦击敌位左侧之位。");
            AddTranslation("Siphon", "汲威");
            AddTranslation("Creatures to the left of [creature] lose all attack power. That attack power is instead added to this card's power.", "[creature]左之诸物尽失威；其威转加于此牌。");
            AddTranslation("Skin Animator", "皮灵");
            AddTranslation("While [creature] is alive on the board, all pelts gain it's attack power.", "[creature]生而在场，则诸革皆得其威。");
            AddTranslation("Skull Swarm", "骷潮");
            AddTranslation("While [creature] is alive and on the board, all Skeletons will strike twice when attacking.", "[creature]生而在场，则诸骷髅击时皆再击。");
            AddTranslation("Slimeball", "黏球");
            AddTranslation("When [creature] is played, it permanently stains the opposing slot with slime. Any creatures in a slimy slot without made of stone lose 1 power.", "[creature]陈时，永以黏污敌位。凡在黏位而非石躯之物，皆失1威。");
            AddTranslation("Snapshot", "瞬录");
            AddTranslation("When [creature] perishes, the entire board reverts to the state it was in when [creature] was placed.", "[creature]亡，则全场复归其陈时之状。");
            AddTranslation("Snare", "陷缚");
            AddTranslation("When [creature] is played opposite a creature, that creature is ensnared and stored within the bearer, being released when the bearer perishes.", "[creature]若陈于物对位，则缚彼物于持者之内；持者亡而后释。");
            AddTranslation("Snip", "裁断");
            AddTranslation("When [creature] is played, the creature opposing it is removed from the board without triggering on-death effects.", "[creature]陈时，敌对之物去场，不发死效。");
            AddTranslation("[creature] cuts it's opponent in half.", "[creature]裂其敌为二。");
            AddTranslation("Soak", "浸");
            AddTranslation("Any damage taken by [creature] is reduced by 1. Taking damage decrements the timer rendered on this sigil. When the timer rendered on this sigil reaches 0, the bearer will attack with power equal to it's health, then perish.", "[creature]所受之伤减1。受伤则减此印之计；计至0，持者将以等于其命之威击，继而亡。");
            AddTranslation("Spiders Web", "蛛网");
            AddTranslation("When any opponent card moves, with the exception of entering the board for the first time,[creature] will strike them for one damage.", "凡敌牌移，初入场者除外，[creature]皆击之，伤1。");
            AddTranslation("Splash Damage", "溅伤");
            AddTranslation("When [creature] strikes a slot, creatures to the left and right of the struck slot will be dealt 1 damage.", "[creature]击一位，则其左右诸物各受1伤。");
            AddTranslation("Splash Zone", "溅域");
            AddTranslation("When [creature] is struck, the creatures to it's left or right are also dealt 1 damage.", "[creature]被击，则左右诸物亦各受1伤。");
            AddTranslation("The damage dealt to [creature] splashes out to its comrades.", "加诸[creature]之伤，亦溅其众。");
            AddTranslation("Split Detonation", "裂爆");
            AddTranslation("When [creature] dies, diagonally adjacent enemy creatures are dealt 10 damage.", "[creature]死，则对角邻敌物受10伤。");
            AddTranslation("Split Sentry", "裂哨");
            AddTranslation("When a creature moves into the space opposing [creature], any creatures to their left or right are dealt 1 damage.", "有物入[creature]对位，则其左右诸物各受1伤。");
            AddTranslation("Spurred", "催势");
            AddTranslation("[creature] gains 1 power while the slot opposing it is occupied.", "[creature]对位有物，则得+1威。");
            AddTranslation("Squirrel Dependent", "倚鼠");
            AddTranslation("If [creature]'s owner controls no Squirrels, [creature] will perish. If this card is a squirrel, it cannot support itself.", "若[creature]之主无松鼠，则[creature]亡。若此牌为松鼠，则不能自立。");
            AddTranslation("Squirrel King", "鼠王");
            AddTranslation("When [creature] attacks an opposing creature, a squirrel is created in the owner's hand.", "[creature]击敌物，则于主手生一松鼠。");
            AddTranslation("Stalwart", "坚毅");
            AddTranslation("If [creature] is moved from the space it was placed in, it will immediately move back, shunting any card which may have moved there in the meantime out of the way.", "若[creature]自其初位移，则立复其位；期间若有他牌入彼位，皆被挤开。");
            AddTranslation("Sticky Trail", "黏迹");
            AddTranslation("When [creature] enters a space on the board, it permantently marks that space with its slime. Any creatures that enter that space without the Made of Stone sigil lose 1 power.", "[creature]入场上一位，则永以黏污之。后入其位而无石躯印者，失1威。");
            AddTranslation("Sturdy", "坚躯");
            AddTranslation("All damage taken by [creature] is reduced by 1.", "[creature]所受之伤减1。");
            AddTranslation("Subaquatic Spines", "潜刺");
            AddTranslation("[creature] will submerge during the opponent's turn. While submerged, opposing creatures attack it's owner directly, and will take 1 damage after attacking.", "[creature]于敌合潜。潜时，敌物直击其主，且击后受1伤。");
            AddTranslation("Summoner", "召者");
            AddTranslation("When [creature] is played, it's owner may choose from a selection of random cards to add to their hand.", "[creature]陈时，其主可自随机牌中择一入手。");
            AddTranslation("Supercharge", "满充");
            AddTranslation("When [creature] is played, it refreshes it's owner's energy to the current maximum.", "[creature]陈时，复其主之能至今上限。");
            AddTranslation("[creature] restores it's owner's energy.", "[creature]复其主之能。");
            AddTranslation("Surging Quills", "涌刺");
            AddTranslation("When [creature] is struck, the striker is dealt damage equal to the amount of times this has been struck.", "[creature]被击，则击者受伤，等于其所受击数。");
            AddTranslation("Sweeping Strike Left", "左横击");
            AddTranslation("[creature] will always attack the leftmost opponent creature. Overkill damage travels to the right instead of to the backlane.", "[creature]恒击敌最左之物。溢伤不入后列，而右行。");
            AddTranslation("Sweeping Strike Right", "右横击");
            AddTranslation("[creature] will always attack the rightmost opponent creature. Overkill damage travels to the left instead of to the backlane.", "[creature]恒击敌最右之物。溢伤不入后列，而左行。");
            AddTranslation("Switch Strike", "转击");
            AddTranslation("At the end of its owners turn [creature] will alternate between striking to the left or right of the opposing slot when it attacks, in addition to striking the opposing slot.", "至主合末，[creature]击时，除击对位外，兼交替击其左或右邻。");
            AddTranslation("Swooping Strike", "俯击");
            AddTranslation("[creature] will strike the opposing space a second time when attacking. Also, [creature]'s first strike each turn will occur directly, over opponent creatures.", "[creature]击敌位时复击一次。且其每合首击，直越敌物而至。");
            AddTranslation("Telepathic", "心通");
            AddTranslation("While [creature] is on the board, all friendly creatures will stike the most powerful opponent card when they attack.", "[creature]在场，则友物击时皆取敌最强者。");
            AddTranslation("Tempting Target", "诱靶");
            AddTranslation("If an opponent creature would strike a space adjacent to [creature], it will instead strike [creature].", "若敌物欲击[creature]之邻位，则转击[creature]。");
            AddTranslation("Termatriarch", "蚁后");
            AddTranslation("While [creature] and a different card bearing the Termite King sigil are alive and on the board, a termite will be created in your hand at the start of your turn.", "[creature]与他牌之蚁王印者同生在场，则汝合初生一白蚁于手。");
            AddTranslation("Termite King", "蚁王");
            AddTranslation("While [creature] and a different card bearing the Termatriarch sigil are alive and on the board, a termite will be created in your hand at the start of your turn.", "[creature]与他牌之蚁后印者同生在场，则汝合初生一白蚁于手。");
            AddTranslation("TestSigil", "试印");
            AddTranslation("[creature] will most likely fuck shit up.", "[creature]大抵将大乱其局。");
            AddTranslation("Thief", "盗");
            AddTranslation("[creature] will grant an amount of currency when it kills another creature.", "[creature]杀他物，则得若干币。");
            AddTranslation("Time Travel", "时渡");
            AddTranslation("While [creature] is played, the opponent is obligated to skip their next turn.", "[creature]陈时，敌必失其下合。");
            AddTranslation("I'll pass my next turn.", "余下合不行。");
            AddTranslation("Your opponent must skip their next turn!", "汝敌下合必失！");
            AddTranslation("Ugh. Fine. I'll pass.", "唉。可，余下合不行。");
            AddTranslation("Fair enough dear, I'll pass.", "然，亲者，余下合不行。");
            AddTranslation("Tooth Puller", "拔齿");
            AddTranslation("At the end of the owner's turn, [creature] will add one damage to the scales in the owner's favour, regardless of it's attack power or obstruction.", "至主合末，[creature]必为主之衡增1伤，不计其威与阻。");
            AddTranslation("Toxic", "剧毒");
            AddTranslation("When [creature] is struck but does not perish, the striker perishes. Does not affect Made of Stone cards.", "[creature]被击而不亡，则击者亡。石躯牌不受其害。");
            AddTranslation("[creature]s toxicity kills instantly!", "[creature]之毒，触即亡！");
            AddTranslation("Traitor", "叛徒");
            AddTranslation("When [creature] is played, it will move onto the opponent's side of the board if unobstructed.", "[creature]陈时，若无阻，则移入敌场。");
            AddTranslation("Trajectile Quills", "追刺");
            AddTranslation("When [creature] is struck, an opponent creature of the owner's choosing is dealt 1 damage.", "[creature]被击，则主择一敌物，令受1伤。");
            AddTranslation("Trampler", "践踏");
            AddTranslation("At the end of the owner's turn, [creature] will move in the direction inscribed on the sigil. Cards in the way will be killed, and grant +1 attack power to the sigil bearer.", "至主合末，[creature]循印所书之向而行。所当之牌皆亡，且令持印者得+1威。");
            AddTranslation("Transformer", "变形");
            AddTranslation("At the end of the turn, [creature] will transform to or from it's alternate form.", "至合末，[creature]将化为其异形，或自异形返之。");
            AddTranslation("Transmogrification", "易形");
            AddTranslation("When [creature] strikes a creature, that creature will be changed into another form.", "[creature]击物，则彼物易为他形。");
            AddTranslation("Trapjaw", "阱颚");
            AddTranslation("[creature] will attack to the left and the right of the opposing space if those slots are obstructed. If those slots are not obstructed, the strikes will be transferred to the directly opposing space.", "若[creature]对位之左右有阻，则击其左右；若无阻，则转击正对之位。");
            AddTranslation("Trifling Sacrifice", "双血");
            AddTranslation("[creature] counts as 2 Blood rather than 1 Blood when sacrificed.", "[creature]为祀时，计2血，不计1血。");
            AddTranslation("Trio", "三连");
            AddTranslation("When [creature] is played, a copy of it is created to the left and right.", "[creature]陈时，左右各生其副本一。");
            AddTranslation("Triple Strike", "三击");
            AddTranslation("[creature] will strike the opposing space two extra times when attacking.", "[creature]击时，复击对位二度。");
            AddTranslation("Trophy Hunter", "猎赏");
            AddTranslation("[creature] will target the most powerful opposing card when it attacks.", "[creature]击时，必取敌中最强者。");
            AddTranslation("Tuck And Roll", "卷滚");
            AddTranslation("At the end of combat, [creature] will move to the free space opposed by the least amount of attack power, taking into account queued creatures, flight, and Touch of Death.", "战终，[creature]移至对面威最寡之空位，计及后列诸物、翔袭与触死。");
            AddTranslation("Tug", "牵引");
            AddTranslation("When [creature] is played, it will draw the queued opposing creature into the main opposing space, if possible.", "[creature]陈时，若可，则引后列敌物入正对位。");
            AddTranslation("Twin Bond", "双缚");
            AddTranslation("When [creature] is played, a copy of it is created adjacent, killing other creatures to make room if there is none. These cards share a health pool, and when either card dies, it's twin will die as well.", "[creature]陈时，邻位生其副；若无位，则杀他物以辟之。二者共一命池；其一既亡，则其双亦亡。");
            AddTranslation("Twister", "旋变");
            AddTranslation("When struck, [creature] will transform to or from it's alternate form.", "[creature]被击，则化为其异形，或自异形返之。");
            AddTranslation("Unbalanced Leadership", "偏领");
            AddTranslation("The creature directly to the left of [creature] gains 2 power.", "[creature]左直邻之物得+2威。");
            AddTranslation("Under Pressure", "受压");
        }
    }
}
