using DiskCardGame;
namespace ClassicChineseLanguagePack
{
    internal static class InscryptionModsBatch30
    {
        private static void AddTranslation(string english, string classical)
        {
            ClassicChineseLanguagePackPlugin.Translate(
                ClassicChineseLanguagePackPlugin.GUID, null, english, classical, Language.ChineseSimplified);
        }

        public static void RegisterTranslations()
        {
            // AllTheSigilsMod (final)
            AddTranslation("[creature] will attack as soon as it gets played on the board. It will not attack during normal combat. It will attack at the start of the owner's turn.", "[creature]既陈即攻。常战之时则不攻，而于持牌者合始攻。");
            AddTranslation("Herd", "滋群");
            AddTranslation("[creature] will summon a copy of itself each upkeep, up to three times.", "[creature]每合始生一己身之副于同侧空位，至三而止。");
            AddTranslation("Hermit", "隐");
            AddTranslation("[creature] may be placed on any terrain card. If it is their sigils and stats will be combined, and a name combination will be created.", "[creature]可陈于诸地形牌上。若然，则并其印与数，而成一合名。");
            AddTranslation("High Tide", "潮涨");
            AddTranslation("While [creature] is on the board, it will grant the waterborne sigil of cards that are played after it on it's side of the board. Does not affect cards that are Airborne.", "凡[creature]在局，后陈于其侧之牌皆得潜袭印契。翔袭者不与。");
            AddTranslation("The waters rise.", "潮起矣。");
            AddTranslation("Homing", "趋的");
            AddTranslation("If the opposing slot is empty, and there is a creature in a neighbouring lane, [creature] will attack that creature instead of attacking the opposing slot.", "其对位若空，而邻列有物，则[creature]击彼物，不直击敌主。");
            AddTranslation("Hoodini", "幻换");
            AddTranslation("When [creature] is played, it will swap places with the opposing creature.", "[creature]既陈，则与其对物易位；若彼处无牌，则径赴敌侧。");
            AddTranslation("Host", "巢");
            AddTranslation("[creature] is the host of other creatures. It will give you such creature when struck.", "[creature]为他物之巢。见击，则予汝其物。");
            AddTranslation("[creature] will cause the opponant to skip their turn when played.", "[creature]既陈，使敌过其一合。");
            AddTranslation("The sands of time tic away", "时沙渐尽。");
            AddTranslation("Exhaustion", "惫");
            AddTranslation("The attack of [creature] will be decreased by the same amount as its lost health.", "[creature]之威，减如其所失之命。");
            AddTranslation("Hyped", "奋");
            AddTranslation("[creature] will attack at the start of the owner's turn in addition to during normal combat.", "[creature]除常战时攻外，亦于持牌者合始攻。");
            AddTranslation("Imbuing", "赋灵");
            AddTranslation("[creature] will get specific buffs depending on which tribe is most promenent in the sacrifices that were used to summon it.", "[creature]所受之益，视召之所用牺牲中何属最著而定。");
            AddTranslation("Inaccurate", "失准");
            AddTranslation("[creature] will strike a random one of the opposing spaces to the left and right of the spaces across from it as well as the space in front of it.", "[creature]漫击其对位及其左右之一处。");
            AddTranslation("Old Timer", "老成");
            AddTranslation("At the Start of its owner's turn [creature] will gain +1 attack and will take 1 damage.", "持牌者合始，[creature]威益一，而受一伤。");
            AddTranslation("Injured", "伤");
            AddTranslation("[creature] is hurt and will lose 1 health each time it declares an attack due to the strain of the injuries.", "[creature]每宣攻，皆以其伤势失一命。");
            AddTranslation("Instant", "立尽");
            AddTranslation("[creature] will perish immediately after its played.", "[creature]既陈即灭。");
            AddTranslation("Launcher", "发物");
            AddTranslation("At the end of its owner's turn, [creature] will create another creature on a random empty space on the owner's side of the table.", "持牌者合终，[creature]于其侧一偶空位生别物。");
            AddTranslation("Lead (Bones)", "骨导");
            AddTranslation("Pay 2 bones to move this card one slot in the direction inscribed on the sigil.", "费二骨，使此牌循印所志之向移一位。");
            AddTranslation("one can lead  a horse to water...", "人能引马临水……");
            AddTranslation("Lead (Energy)", "能导");
            AddTranslation("Pay 2 energy to move this card one slot in the direction inscribed on the sigil.", "费二能，使此牌循印所志之向移一位。");
            AddTranslation("Leech", "蛭");
            AddTranslation("When [creature] deals damage, it will heal 1 Health for each damage dealt to a card.", "[creature]出伤时，凡伤一牌一分，则复一命。");
            AddTranslation("Vigor from blood!", "力生于血！");
            AddTranslation("Left scratch", "左爪");
            AddTranslation("When [creature] attacks it will also attack the space on the left of the attacked slot.", "[creature]攻时，亦及左旁之位。");
            AddTranslation("Life Gambler", "赌命");
            AddTranslation("At the end of the owner's turn, [creature] will deal 2 damage to the owner in exchange for a 0 to 6 increase in stats. Failing to pay this cost will result in death.", "持牌者合终，[creature]伤其主二，以易数值益零至六；不能偿此，则死。");
            AddTranslation("Your blood, their strength!", "汝血，彼威！");
            AddTranslation("Linguist", "舌师");
            AddTranslation("While [creature] is on the board, all talking cards on your side of the board get +1 attack.", "凡[creature]在局，汝侧诸言牌威益一。");
            AddTranslation("Low Tide", "潮退");
            AddTranslation("While [creature] is on the board, it will negate the waterborne sigil of cards that are played after it on it's side of the board.", "凡[creature]在局，后陈于其侧之牌，其潜袭印契皆废。");
            AddTranslation("Lullaby", "眠谣");
            AddTranslation("When [creature] dies, all opposing creatures gain the asleep sigil.", "[creature]死，则敌诸物皆得寐印。");
            AddTranslation("Maneuver", "调行");
            AddTranslation("At the start of the owner's turn, [creature] will strafe in the direction inscribed on the sigil if there is a creature in the opposing slot from it. Else it will strafe in the opposite direction inscribed on the sigil.", "持牌者合始，若[creature]对位有物，则循印所志之向移；不然，则反向而移。");
            AddTranslation("It runs", "奔矣。");
            AddTranslation("Medic", "医");
            AddTranslation("At the start of the owner's turn, [creature] will try heal 1 damage to a friendly card for each instance of Medic.", "持牌者合始，[creature]每因一重医，尝疗一友牌之一伤。");
            AddTranslation("A good patching", "其疗善矣。");
            AddTranslation("Medical Aid", "救疗");
            AddTranslation("At the end of the opponent's turn, choose a hurt creature on the owner's side to heal for 1.", "敌合终，持牌者择一受伤之己物，疗之以一命。");
            AddTranslation("Midas", "点金");
            AddTranslation("[creature] kills a creature, it will generate 1 Foil for each instance of Midas the card has.", "[creature]杀一物，则此牌每有一点金，生一箔。");
            AddTranslation("A bounty, paid in full.", "赏已尽偿。");
            AddTranslation("Mount", "载");
            AddTranslation("Cards may be played on top of [creature]. If they are their sigils and stats will be combined, and a name combination will be created.", "诸牌可陈于[creature]之上。若然，则并其印与数，而成一合名。");
            AddTranslation("Power from Movement", "动益");
            AddTranslation("At the start of the owner's turn, [creature] will gain 1 power and 1 health if it moved last round.", "持牌者合始，若[creature]上合尝移，则威命各益一。");
            AddTranslation("Each move, it grows", "每移而长。");
            AddTranslation("Nurse", "护医");
            AddTranslation("At the end of the opponent's turn, [creature] will heal any adjacent friendly cards.", "敌合终，[creature]疗其左右己牌。");
            AddTranslation("Nutritious", "饶养");
            AddTranslation("When [creature] is sacrificed, it adds 1 power and 2 health to the card it was sacrificed for.", "[creature]祀时，所为而陈之牌威益一，命益二。");
            AddTranslation("That creature is so full of nutrients, the creature you play comes in stronger!", "彼物饶养，故汝所陈者益强！");
            AddTranslation("Bone hoarder 1", "藏骨一");
            AddTranslation("When [creature] is played, 1 bone is rewarded.", "[creature]既陈，则其主持得一骨。");
            AddTranslation("Opportunist", "乘隙");
            AddTranslation("[creature] will gain 1 power for each instance of Opportunist, when the opposing slot is empty.", "其对位若空，[creature]每因一重乘隙而威益一。");
            AddTranslation("It takes it's chance when it gets it.", "得隙则乘之。");
            AddTranslation("Paralysis", "瘫");
            AddTranslation("[creature] will only attack every other turn. Some effects from sigils may bypass this.", "[creature]隔合乃攻。诸印之效或能逾此。");
            AddTranslation("A shocking event.", "骇矣。");
            AddTranslation("Parasite", "寄");
            AddTranslation("[creature] may be placed on top of any card. If it is their sigils and stats will be combined, and a name combination will be created.", "[creature]可陈于诸牌之上。若然，则并其印与数，而成一合名。");
            AddTranslation("Pathetic Sacrifice", "鄙祭");
            AddTranslation("[creature] is so pathetic, it is not a worthy or noble sacrifice. [creature] is meant to stay on the board, and thus can't be targeted by the hammer.", "[creature]甚鄙，不为堪祀，亦非贵祭。[creature]当留于局，故锤不得指之。");
            AddTranslation("That is not a noble, or worthy sacrifice", "此非贵祭，亦非堪祀。");
            AddTranslation("Picky", "择");
            AddTranslation("[creature] cannnot be summoned by using any free cards as sacrifice.", "[creature]不得以无费牌为牲而召。");
            AddTranslation("Pierce", "贯");
            AddTranslation("[creature] attacks the card in queue behind it's initial target first when declaring an attack.", "[creature]宣攻时，先贯其初所攻者之后列之牌。");
            AddTranslation("My creatures!", "吾物！");
            AddTranslation("Poisonous", "毒");
            AddTranslation("When [creature] perishes, the creature that killed it perishes as well.", "[creature]死，则杀之者亦死。");
            AddTranslation("Attacking something poisonous, isn't that smart.", "攻毒物，非智也。");
            AddTranslation("Possessor", "附");
            AddTranslation("When [creature] perishes, it will grant a random friendly card that is on the board it's base power and health.", "[creature]死，则以其本威与本命授局上一偶友牌。");
            AddTranslation("It passes it's strength onto those who remain", "其遗其力于存者。");
            AddTranslation("Powerful Possessor", "强附");
            AddTranslation("When [creature] perishes, it will grant a random friendly card that is on the board it's base plus modified power and base plus modified health.", "[creature]死，则以其今威与今命授局上一偶友牌。");
            AddTranslation("Predator", "掠");
            AddTranslation("[creature] will gain 1 power for each instance of Predator, when the opposing slot has a card.", "其对位有牌，则[creature]每因一重掠而威益一。");
            AddTranslation("Prideful", "骄");
            AddTranslation("[creature] will not attack a card with a power 2 lower than its own.", "[creature]不攻威下己二之牌。");
            AddTranslation("A creature's pride will be it's downfall.", "物之骄，其败也。");
            AddTranslation("Protector", "佑");
            AddTranslation("[creature] will attacks on adjacent allies to hit directly.", "[creature]在局，则攻其邻友者，皆直中其主。");
            AddTranslation("They protect their allies, but who protects you?", "彼护其友，谁护汝？");
            AddTranslation("Puppets gift", "傀礼");
            AddTranslation("As long as [creature] is on the board any cards with brittle won't die because of brittle.", "凡[creature]在局，有脆骨之牌不以脆骨而死。");
            AddTranslation("Superior Sacrifice", "上祭");
            AddTranslation("[creature] is counted as 4 blood rather than 1 blood when sacrificed.", "[creature]祀时计四血，不一。");
            AddTranslation("Ram", "触");
            AddTranslation("[creature] will try to ram the card infront of it when played, or every upkeep till it succeeds once. It will send the rammed target to the queue if on my side, or back to the hand if on your side. Does not work during combat.", "[creature]既陈，则尝触其前之牌；不成则每合始复然，至一成而止。此牌若在我侧，则所触者却于后列；若在汝侧，则反之于手。战时无效。");
            AddTranslation("Moving creatures around? How Rude!", "移物耶？无礼甚矣！");
            AddTranslation("Random Strafe", "偶移");
            AddTranslation("[creature] is drawn, it will gain a random strafe sigil.", "[creature]既引，则得一偶移印。");
            AddTranslation("How will it move?", "其将安移？");
            AddTranslation("Recoil", "反震");
            AddTranslation("[creature] will take 1 damage each time they attack.", "[creature]每攻，受一伤。");
            AddTranslation("The strength causes the creature pain.", "其威反伤其身。");
            AddTranslation("Regen 1", "复一");
            AddTranslation("At the end of the owner's turn, [creature] will regen 1 health.", "持牌者合终，[creature]复一命。");
            AddTranslation("This creature will heal 1 Health at the end of it's owner's turn.", "此物于其主合终复一命。");
            AddTranslation("Regen 2", "复二");
            AddTranslation("At the end of the owner's turn, [creature] will regen 2 health.", "持牌者合终，[creature]复二命。");
            AddTranslation("This creature will heal 2 Health at the end of it's owner's turn.", "此物于其主合终复二命。");
            AddTranslation("Regen 3", "复三");
            AddTranslation("At the end of the owner's turn, [creature] will regen 3 health.", "持牌者合终，[creature]复三命。");
            AddTranslation("This creature will heal 3 Health at the end of it's owner's turn.", "此物于其主合终复三命。");
            AddTranslation("Regen", "尽复");
            AddTranslation("At the end of the owner's turn, [creature] will regen to full health.", "持牌者合终，[creature]命尽复。");
            AddTranslation("This creature will heal to full Health at the end of it's owner's turn.", "此物于其主合终命尽复。");
            AddTranslation("Repellant", "斥");
            AddTranslation("When [creature] perishes, the creature that killed it gets pushed into the back row.", "[creature]死，则杀之者却于后列。");
            AddTranslation("Resistant", "耐");
            AddTranslation("[creature] will only ever take 1 damage from most things. Some effects might bypass this.", "[creature]凡所受伤，多不过一；诸效或能逾此。");
            AddTranslation("A hardy creature that one is.", "此物诚强。");
            AddTranslation("Resourceful", "余用");
            AddTranslation("When [creature] is sacrificed, instead of dying, it loses a random sigil. Resourceful will only remove itself when there are no other sigils on the card.", "[creature]见祀不死，惟失一偶印；诸印既尽，余用乃自去。");
            AddTranslation("Retaliate", "报击");
            AddTranslation("[creature] will strike those who strike their adjacent allies.", "[creature]击诸攻其邻友者。");
            AddTranslation("Right scratch", "右爪");
            AddTranslation("When [creature] attacks it will also attack the space on the right of the attacked slot.", "[creature]攻时，亦及右旁之位。");
            AddTranslation("Rushing march", "疾行");
            AddTranslation("At the end of its owner's turn, [creature] will move in the direction inscribed on the sigil, however if it hits a card whilst moving, [creature] will stop and the card it hit will perish.", "持牌者合终，[creature]循印所志之向而移；若移时触牌，则止，而所触者死。");
            AddTranslation("Schooling", "同潜");
            AddTranslation("[creature] will grant creatures with the waterborn 1 power.", "[creature]使有潜袭印之物威益一。");
            AddTranslation("The waterborn stick together.", "潜者相附。");
            AddTranslation("When [creature] is played, a targeted card cut in two.", "[creature]既陈，可剖所择一牌为二。");
            AddTranslation("My card!", "吾牌！");
            AddTranslation("Shapeshifter", "易形");
            AddTranslation("[creature] is ever changing. It will change its form once it's struck.", "[creature]常变。见击，则易其形。");
            AddTranslation("Short", "短");
            AddTranslation("[creature] will not be blocked by an opposing creature bearing the airborn sigil.", "[creature]不为有翔袭之敌物所阻。");
            AddTranslation("Sickness", "疾");
            AddTranslation("[creature] will loose 1 attack each time it declares an attack.", "[creature]每宣攻，失一威。");
            AddTranslation("The creature's strength leaves it as it strikes.", "其击也，威去之。");
            AddTranslation("Bone lord 6", "骨王六");
            AddTranslation("When [creature] dies, 6 bones are rewarded instead of 1.", "[creature]死，则赏骨六，不一。");
            AddTranslation("Sluggish", "缓");
            AddTranslation("[creature] will not attack during normal combat. It will instead attack after the Opponent's cards attack.", "[creature]常战不攻；俟敌牌既攻而后攻。");
            AddTranslation("A bit slow there eh?", "少缓矣？");
            AddTranslation("Song of sleep", "眠歌");
            AddTranslation("If a creature moves into the space opposing [creature], that creature will obtain the asleep sigil.", "若有物移至[creature]对位，则彼得寐印。");
            AddTranslation("Spawner", "生行");
            AddTranslation("At the end of its owner's turn, [creature] will move in the direction inscribed on the sigil and will create another creature in its old space.", "持牌者合终，[creature]循印所志而移，而故处生别物。");
            AddTranslation("Stampede", "驰攻");
            AddTranslation("[creature] will cause adjacent creatures to attack when played on the board if played not during combat.", "[creature]若于战外既陈，则使其旁诸物出击。");
            AddTranslation("Power in Numbers", "众则有力。");
            AddTranslation("Sticky", "胶");
            AddTranslation("If the card opposing [creature] moves, [creature] will try to move with it", "若[creature]对位之牌移，[creature]亦尝从之。");
            AddTranslation("Velocity", "迅");
            AddTranslation("At the end of the owner's turn, [creature] will move in the direction inscribed in the sigil. If it is able to move, it will gain 1 power and 1 health.", "持牌者合终，[creature]循印所志而移；若能移，则威命各益一。");
            AddTranslation("Strong Wind", "烈风");
            AddTranslation("If [creature] is on the board, negate the airbone sigil of all cards that are played after it.", "凡[creature]在局，后陈之牌，其翔袭印皆废。");
            AddTranslation("The Wind forces a landing.", "风迫其降。");
            AddTranslation("Submerged Ambush", "潜伏");
            AddTranslation("[creature] will deal 1 damage to cards that attacked over it while it was face-down. Does not affect cards that are Airborne.", "[creature]翻伏时，凡越其位而攻者，受一伤；翔袭者不与。");
            AddTranslation("It strikes from the water.", "出击于水中。");
            AddTranslation("Swallower", "吞");
            AddTranslation("After [creature] attacks, it will destroy the card it attacks if it has less health than it and heal to full health.", "攻后，若所攻之牌命少于[creature]，则毁之，而[creature]命尽复。");
            AddTranslation("Gone in one gulp.", "一啜而尽。");
            AddTranslation("Sympathetic", "恤");
            AddTranslation("[creature] will only attack if the opposing creature has more or equal health to it.", "[creature]惟对物之命不少于己，乃攻。");
            AddTranslation("Take-Off (Bones)", "骨翔");
            AddTranslation("Pay 2 bones to give this card Airborne till the start of owner's next turn.", "费二骨，使此牌至其主持次合始得翔袭。");
            AddTranslation("Spread your wings and fly.", "展翼而翔。");
            AddTranslation("Take-Off (Energy)", "能翔");
            AddTranslation("Pay 2 energy to give this card Airborne till the start of the owner's next turn.", "费二能，使此牌至其主持次合始得翔袭。");
            AddTranslation("Terrified", "骇遁");
            AddTranslation("When a creature moves into the space opposing [creature], [creature] will move away from that card to a random free adjacent spot while pushing any creatures in it's way, while prioritizing slots without any opposing creatures.", "有物移至与[creature]相对之位，则[creature]避彼而移于一邻空位；道有诸物，则推之；先择无对物者。");
            AddTranslation("Thick Shell", "厚甲");
            AddTranslation("When attacked, [creature] takes 1 less damage.", "[creature]见攻，则所受伤少一。");
            AddTranslation("The thick shell on that creature protected it from one damage!", "其厚壳为之省一伤！");
            AddTranslation("[creature] will try to steal a random default sigil from a card in the opposing lane when played, or at the start of the owner's turn until it does.", "[creature]既陈，或持牌者合始，尝自其对列之一牌窃一偶常印，至得乃止。");
            AddTranslation("If only I could steal the moon...", "若得窃月则善矣……");
            AddTranslation("Bone prince 3", "骨侯三");
            AddTranslation("When [creature] dies, 3 bones are rewarded instead of 1.", "[creature]死，则赏骨三，不一。");
            AddTranslation("Bone hoarder 3", "藏骨三");
            AddTranslation("When [creature] is played, 3 bones are rewarded.", "[creature]既陈，则其主持得三骨。");
            AddTranslation("Tooth Bargain", "齿约");
            AddTranslation("When [creature] is played, it will put 1 point of damage of it's opponent's side of the scale. When it perishes, it will put 2 damage on the owner's side of the scale.", "[creature]既陈，则敌衡加一伤；其死，则其主衡加二伤。");
            AddTranslation("A deal with a devil I see...", "盖与鬼神为约也……");
            AddTranslation("Toothpuller", "抽齿");
            AddTranslation("At the end of the owner's turn, [creature] will add one point of damage to the opponent's scale.", "持牌者合终，[creature]使敌衡加一伤。");
            AddTranslation("That Hurts", "痛哉。");
            AddTranslation("Tooth Shard", "齿屑");
            AddTranslation("[creature] will generate 1 foil when hit, if it lives through the attack.", "[creature]见击而不死，则生一箔。");
            AddTranslation("A splinter of gold.", "金之一屑。");
            AddTranslation("Toxin", "毒");
            AddTranslation("When [creature] damages another creature, that creature looses 1 power and 1 health.", "[creature]伤他物，则彼失一威一命。");
            AddTranslation("All things can be worn down, and in different ways.", "物皆可磨，而其途不同。");
            AddTranslation("Toxin (Deadly)", "死毒");
            AddTranslation("When [creature] damages another creature, that creature gains the Dying Sigil. The Dying Sigil is defined as: [creature] will die after 2 number of turns.", "[creature]伤他物，则彼得将死印。将死印者：历二合而死。");
            AddTranslation("Even once combat is over, it leaves a deadly mark", "战罢犹遗死痕。");
            AddTranslation("Toxin (Sickening)", "疾毒");
            AddTranslation("When [creature] damages another creature, that creature gains the Sickness Sigil. The Sickness Sigil is defined as: When ever a creature bearing this sigil declares an attack, they will loose one attack.", "[creature]伤他物，则彼得疾病印。疾病印者：凡有此印之物，每宣攻失一威。");
            AddTranslation("Even once combat is over, it leaves sickness spreads in what it fights.", "战罢犹遗其疾于所斗者。");
            AddTranslation("Toxin (Strength)", "削威毒");
            AddTranslation("When [creature] damages another creature, that creature looses 1 power.", "[creature]伤他物，则彼失一威。");
            AddTranslation("Even once combat is over, strength leaves it's target", "战罢犹使其靶失威。");
            AddTranslation("Toxin (Vigor)", "削命毒");
            AddTranslation("When [creature] damages another creature, that creature looses 1 health.", "[creature]伤他物，则彼失一命。");
            AddTranslation("Trample", "蹂");
            AddTranslation("When [creature] deals overkill damage to a card, the overkill damage will be sent to the owner.", "[creature]溢伤及其主。");
            AddTranslation("A stampede can not be stopped.", "驰群不可止。");
            AddTranslation("Transform Chicken (Enemy Only)", "化鸡（敌惟）");
            AddTranslation("[creature] will transform a random creature on the board on the opponent's side into a Chicken. A Chicken is defined as 1 Attack, 1 Health.", "[creature]每持牌者合始，使敌侧一偶物化为鸡。鸡者：1威、1命。");
            AddTranslation("Transform Chicken (Loose Cannon)", "化鸡（全场）");
            AddTranslation("[creature] will transform a random creature on the board into a Chicken. A Chicken is defined as 1 Attack, 1 Health.", "[creature]每持牌者合始，使局上一偶物化为鸡。鸡者：1威、1命。");
            AddTranslation("Transform Chicken (Opposing)", "化鸡（对位）");
            AddTranslation("When a creature is played opposing [creature] it will turn into a Chicken. A Chicken is defined as 1 Attack, 1 Health.", "有物陈于[creature]对位，则化为一鸡。鸡者：1威、1命。");
            AddTranslation("Transient", "旋返");
            AddTranslation("At the end of the owner's turn, [creature] will return to your hand.", "持牌者合终，[creature]反归汝手。");
            AddTranslation("The creature blinks back into the owner's hand at the end of their turn.", "此物合终倏返其主之手。");
            AddTranslation("Tribal Ally", "同属友");
            AddTranslation("When [creature] is played, A card of the same tribe is created in your hand. No tribe counts as a tribe of tribeless.", "[creature]既陈，汝手中生一与之同属之牌。无属者，以无属为属。");
            AddTranslation("It calls for it's kin.", "呼其族矣。");
            AddTranslation("Tribal Tutor", "同属引");
            AddTranslation("When [creature] is played, you may search your deck for a card of the same tribe and take it into your hand. No tribe counts as a tribe of tribeless.", "[creature]既陈，汝可索牌列中与之同属之一牌，取入手。无属者，以无属为属。");
            AddTranslation("Tribe Attack", "属攻");
            AddTranslation("While [creature] is on the board, all other cards on your side of the board of the same tribe will gain +1 attack.", "凡[creature]在局，汝侧余牌与之同属者，威皆益一。");
            AddTranslation("Tribe Health", "属命");
            AddTranslation("While [creature] is on the board, all other cards on your side of the board of the same tribe will gain +1 health.", "凡[creature]在局，汝侧余牌与之同属者，命皆益一。");
            AddTranslation("Turbulent Waters", "湍波");
            AddTranslation("[creature] will force other creatures with waterborne to resurface and take 1 damage at the start of the owner's turn.", "[creature]迫有潜袭印之余物出水；持牌者合始，彼皆受一伤。");
            AddTranslation("The waters be rough.", "波涛甚恶。");
            AddTranslation("Bone prince 2", "骨侯二");
            AddTranslation("When [creature] dies, 2 bones are rewarded instead of 1.", "[creature]死，则赏骨二，不一。");
            AddTranslation("Bone hoarder 2", "藏骨二");
            AddTranslation("When [creature] is played, 2 bones are rewarded.", "[creature]既陈，则其主持得二骨。");
            AddTranslation("Underdog", "居下");
            AddTranslation("[creature] can only be played when you are losing.", "汝处下风，乃得陈[creature]。");
            AddTranslation("Vicious", "狠");
            AddTranslation("When [creature] is attacked, it gains 1 power.", "[creature]见攻，则威益一。");
            AddTranslation("A hit just makes it angry.", "一击适足怒之。");
            AddTranslation("Warper", "越界");
            AddTranslation("At the end of its owner's turn, [creature] will move to the right, jumping over any creatures in its path, if it encounters the edge of the board, it will loop over to the other side.", "持牌者合终，[creature]右移，越其途诸物；遇局边，则环至彼端。");
            AddTranslation("Wild hunger", "饕行");
            AddTranslation("At the end of its owner's turn, [creature] will move in the direction inscribed on the sigil, however if it hits a card whilst moving, [creature] will stop, the card it hit will perish and [creature] will gain 1+/1+.", "持牌者合终，[creature]循印所志而移；若移时触牌，则止，所触者死，而[creature]威命各益一。");
            AddTranslation("Withering", "枯");
            AddTranslation("[creature] will perish at the end of the opponant's turn.", "[creature]于敌合终灭。");
            AddTranslation("Zapper", "痹触");
            AddTranslation("When [creature] damages another creature, that creature will gain the Paralysis Sigil. The Paralysis sigil is defined as: A card bearing this sigil will only attack every other turn.", "[creature]伤他物，则彼得瘫印。瘫印者：有此印之牌，隔合乃攻。");
            // BittysSigilsMod
            AddTranslation("Blocked on both sides. No Eggs for you.", "两旁既塞，无卵与汝。");
            AddTranslation("No empty spaces. No firs for you.", "无空位，无杉与汝。");
            AddTranslation("Explosive Squirrel Reproduction", "蕃鼠");
            AddTranslation("When [creature] is played, fill your side deck with squirrels.", "[creature]既陈，则以松鼠充汝副牌列。");
            AddTranslation("Hauler", "牵");
            AddTranslation("At the end of the owner's turn, [creature] will move in the direction inscribed in the sigil. Adjacent friendly creatures will be pulled in the same direction.", "持牌者合终，[creature]循印所志而移；其旁友物，亦为之牵而同移。");
            AddTranslation("Heart Swap", "易心");
            AddTranslation("When [creature] is played, all cards on the board swap their power and health.", "[creature]既陈，局上诸牌皆易其威命。");
            AddTranslation("Mutual Hire", "相雇");
            AddTranslation("When [creature] is played, a copy of it is created in the opposing space.", "[creature]既陈，则其对位生一副。");
            AddTranslation("Charged Barrage", "充霰");
            AddTranslation("Pay 4 life to increase the power of all cards on your side of the board by 1.", "费四命，则汝侧诸牌威皆益一。");
            AddTranslation("Health Roll", "命骰");
            AddTranslation("Pay 1 Energy to set the health of [creature] randomly between 1 and 6.", "费一能，使[creature]之命偶定于一至六。");
            AddTranslation("Sigil Roll", "印骰");
            AddTranslation("Pay 4 Life to add a random sigil to [creature].", "费四命，加一偶印于[creature]。");
            AddTranslation("Wildlife Camera", "野影器");
            AddTranslation("When [creature] kills another card, a copy of the killed card is created in your hand.", "[creature]杀他牌，则彼牌之副生于汝手。");
            AddTranslation("Dusty Quill", "尘笔");
            AddTranslation("Whenever a creature dies while [creature] is on the board, a corpse is raised in it's place. Corpses are defined as: 0/1.", "凡[creature]在局，有物死，则其处起一尸。尸者：0威、1命。");
            AddTranslation("Bleached Brush", "素笔");
            AddTranslation("When [creature] is played, the opposing card will lose all its sigils.", "[creature]既陈，其对牌尽失诸印。");
            AddTranslation("Strong Soul", "强魂");
            AddTranslation("[creature] may not recieve sigils from another card.", "[creature]不得受他牌之印。");
            AddTranslation("Weak Soul", "弱魂");
            AddTranslation("[creature] may not have its sigils transferred to another card.", "[creature]不得徙己印于他牌。");
            AddTranslation("Nonexistent Soul", "无魂");
            AddTranslation("[creature] may not have sigils transferred to, or from this card.", "[creature]不得受印，亦不得徙印。");
            AddTranslation("Pyrophobia", "惧火");
            AddTranslation("[creature] may not be buffed at campsites.", "[creature]不得于篝火处受益。");
            AddTranslation("Pyrophobia (Attack)", "惧火（威）");
            AddTranslation("[creature] may not recieve power buffs from campsites.", "[creature]不得于篝火处受威益。");
            AddTranslation("Pyrophobia (Health)", "惧火（命）");
            AddTranslation("[creature] may not recieve health buffs from campsites.", "[creature]不得于篝火处受命益。");
            AddTranslation("Repulsion", "斥");
            AddTranslation("[creature] may not attack.", "[creature]不得攻。");
            AddTranslation("Mysterious Mushrooms", "异蕈");
            AddTranslation("At the end of the turn, if there is a card on either side of [creature], they are fused together.", "合终，若[creature]两旁有牌，则并而为一。");
            AddTranslation("At the end of the owner's turn, [creature] will move the opposing card and itself in the direction inscribed in the sigil.", "持牌者合终，[creature]引其对牌与己，循印所志而移。");
            AddTranslation("Counter Attack", "反刺");
            AddTranslation("Once [creature] is struck, the striker is then dealt damage equal to this card's attack.", "[creature]见击，则击者受伤如是牌之威。");
            AddTranslation("Mirror Counter", "镜刺");
            AddTranslation("Once [creature] is struck, the striker is then dealt damage equal to the striker's attack.", "[creature]见击，则击者受伤如其自威。");
            AddTranslation("Board Shifter", "移局");
            AddTranslation("At the end of the owner's turn, [creature] will move in the direction inscribed in the sigil. All cards will shift in the same direction, looping to the other edge of the board.", "持牌者合终，[creature]循印所志而移。诸牌皆同向而移，环至彼边。");
            AddTranslation("Board Shifter (Owner)", "移友局");
            AddTranslation("At the end of the owner's turn, [creature] will move in the direction inscribed in the sigil. Friendly cards will shift in the same direction, looping to the other edge of the board.", "持牌者合终，[creature]循印所志而移。友牌皆同向而移，环至彼边。");
            AddTranslation("Board Shifter (Opposing)", "移敌局");
            AddTranslation("At the end of the owner's turn, [creature] will move in the direction inscribed in the sigil. The opposing cards will shift in the same direction, looping to the other edge of the board.", "持牌者合终，[creature]循印所志而移。敌牌皆同向而移，环至彼边。");
            AddTranslation("Deathbell", "丧钟");
            AddTranslation("At the start of the battle phase, [creature] perishes.", "战阶始，[creature]即灭。");
            AddTranslation("Clockwise", "顺时");
            AddTranslation("When [creature] is played, move all cards on the board clockwise.", "[creature]既陈，局上诸牌皆顺时移一格。");
            AddTranslation("Stubborn", "固");
            AddTranslation("[creature] may not have its stats swapped.", "[creature]不得易其数。");
            AddTranslation("At the end of each turn [creature] is on the board, move all cards on the board clockwise.", "每合终，若[creature]在局，则局上诸牌皆顺时移一格。");
            AddTranslation("Fleeting", "暂");
            AddTranslation("At the end of the turn [creature] will be discarded from your hand.", "合终，[creature]自汝手见弃。");
            AddTranslation("Soul Link", "同魂");
            AddTranslation("When [creature] perishes, all other allied cards bearing this sigil perish as well.", "[creature]灭，则余有此印之友牌皆灭。");
            AddTranslation("Hollow Draw", "虚引");
            AddTranslation("When [creature] is played, discard the oldest card in your hand, draw a card.", "[creature]既陈，弃汝手中最先所引之牌，而更引一牌。");
            AddTranslation("Hollow Barrage", "虚霰");
            AddTranslation("When [creature] is played, all cards take 1 damage.", "[creature]既陈，局上诸牌皆受一伤。");
            AddTranslation("Gem Phobic", "惧玉");
            AddTranslation("If [creature]'s owner controls a Mox card, [creature] perishes.", "若[creature]之主持有玛珂牌，[creature]即灭。");
            AddTranslation("Foolhardy", "妄");
            AddTranslation("[creature] may not recieve modifications from any source.", "[creature]不得受任何改益。");
            AddTranslation("Jumper", "跃");
            AddTranslation("At the end of the owner's turn, [creature] will move itself to the first empty space in the direction inscribed in the sigil.", "持牌者合终，[creature]自循印所志之向移至其首空位。");
            AddTranslation("Super Sprinter", "疾趋");
            AddTranslation("At the end of the owner's turn, [creature] will move itself as far as possible in the direction inscribed in the sigil.", "持牌者合终，[creature]尽所能循印所志而移。");
            AddTranslation("Eggist", "生卵");
            AddTranslation("When [creature] is played, an Egg is created on each empty adjacent space.", "[creature]既陈，其邻空位各生一卵。");
            AddTranslation("Fir Caller", "召杉");
            AddTranslation("When [creature] is played, a Fir is created in each of the owner's spaces.", "[creature]既陈，持牌者诸空位各生一杉。");
            AddTranslation("Flipper", "易数");
            AddTranslation("At the end of the owner's turn, [creature] swaps its stats.", "持牌者合终，[creature]易其数。");
            AddTranslation("Fleeting Draw", "暂引");
            AddTranslation("When [creature] is played, draw 1 card with Fleeting.", "[creature]既陈，则引一有暂印之牌。");
            AddTranslation("Outcast", "还列");
            AddTranslation("At the end of the turn, [creature] is shuffled into the deck.", "合终，[creature]还入汝牌列而乱之。");
            AddTranslation("Hollow Repeater", "虚继");
            AddTranslation("When [creature] perishes, all On Play sigils on that card are activated.", "[creature]灭，则此牌上凡陈时所发之印皆启。");
            AddTranslation("Replenish", "续引");
            AddTranslation("When [creature] is drawn, draw a card.", "[creature]既引，更引一牌。");
            AddTranslation("Target Swap", "易数指");
            AddTranslation("When [creature] is played, Target a Card: the card's stats are swapped.", "[creature]既陈，择一牌而易其威命。");
            AddTranslation("Sacrificial Growth", "祀长");
            AddTranslation("When [creature] is sacrificed, it will grow into a more powerful form.", "[creature]见祀，则长为益强之形。");
            AddTranslation("Ruby Transformer", "红玉化");
            AddTranslation("If [creature]'s owner controls a Ruby Mox, [creature] will be transformed; otherwise [creature] will transform into its base form.", "若[creature]之主持红玉玛珂，则[creature]化其异形；不然，则反其本形。");
            AddTranslation("Gemify", "玉益");
            AddTranslation("[creature] gains buffs based on moxes in play on the owner's side. Orange is 1 Power. Green is 2 Health. Blue is lower Cost.", "[creature]视其主持局中诸玛珂而受益：橙则威益一，绿则命益二，蓝则直降。");
            AddTranslation("Corpse", "尸");
            AddTranslation("TestCard", "试牌");
            // BittysChallengesMod (part 1)
            AddTranslation("Is that a clover?", "彼三叶草乎？");
            AddTranslation("I see.", "然。");
            AddTranslation("Oh?", "噫？");
            AddTranslation("Did you not like having a stacked deck?", "汝不喜牌列偏向乎？");
            AddTranslation("That's fine with me.", "于我可也。");
            AddTranslation("It will be more fair this way anyways.", "如此差为平矣。");
            AddTranslation("oh?", "噫？");
            AddTranslation("my very own ouroboros.", "我之衔尾蛇。");
            AddTranslation("i will be sure to put it to good use.", "我必善用之。");
            AddTranslation("the ouroboros has followed you.", "衔尾蛇随汝来矣。");
            AddTranslation("it's fangs are beared, and it's ready for another fight.", "其牙已露，复可一战。");
            AddTranslation("the unyielding ouroboros has returned,", "不屈之衔尾蛇复来，");
            AddTranslation("growing stronger every death.", "每死而益强。");
            AddTranslation("as inevitable as death,", "如死之必至，");
            AddTranslation("the ouroboros has returned.", "衔尾蛇复来矣。");
            AddTranslation("a serpent slithers out from the undergrowth.", "有蛇蜿蜒出于丛薄。");
            AddTranslation("perhaps you have seen it before?", "汝或尝见之乎？");
            AddTranslation("the ouroboros has died.", "衔尾蛇死矣。");
            AddTranslation("and yet, it will return.", "然终必复归。");
            AddTranslation("the serpent's wrath has been delayed.", "蛇之怒姑缓。");
            AddTranslation("for now.", "姑尔。");
            AddTranslation("the ouroboros only grows stronger from death.", "衔尾蛇惟死而益强。");
            AddTranslation("it will be back.", "终当复来。");
            AddTranslation("a-ah, the sigils...", "啊……其印……");
            AddTranslation("o-oh, the power...", "哦……其威……");
            AddTranslation("a-ah, the health...", "啊……其命……");
            AddTranslation("ah...", "啊……");
            AddTranslation("Chrysomallos, the golden ram.", "克律索马罗斯，金羊也。");
            AddTranslation("what a glorious pelt....", "其革何华也……");
            AddTranslation("The golden ram.", "金羊。");
            AddTranslation("catch it before it escapes.", "其遁前执之。");
            AddTranslation("a rare sight", "罕见也。");
            AddTranslation("it will not stay for long", "不久留也。");
            AddTranslation("what glittering wool,", "其毛灿然，");
            AddTranslation("attached to such a rare creature.", "乃著于此罕物。");
            AddTranslation("oh?", "噫？");
            AddTranslation("a rare chance to get a rare pelt.", "得罕革之机，亦罕矣。");
            AddTranslation("best make the most of it.", "宜尽其机。");
            AddTranslation("You slay the glimmering creature, stealing its pelt.", "汝杀其晶耀之物，而取其革。");
            AddTranslation("The end of such a glorious creature.", "若此华物，竟止于此。");
            AddTranslation("And what a glorious pelt you have obtained.", "而汝所得之革，亦何华也。");
            AddTranslation("Chrysomallos...", "克律索马罗斯……");
            AddTranslation("How tragic your tale is...", "尔事何悲……");
            AddTranslation("To be killed for your pelt...", "竟为其革而见杀……");
            AddTranslation("The Golden Ram lives another day.", "金羊又得一日之生。");
            AddTranslation("Time's up.", "时至矣。");
            AddTranslation("The Golden Ram has found an escape route.", "金羊已得遁路。");
            AddTranslation("The glimmer of the Golden Ram's fur blinds you,", "金羊之毛晶耀眩汝目，");
            AddTranslation("giving it the opportunity to escape.", "故得乘隙而遁。");
            AddTranslation("Ah...", "啊……");
            AddTranslation("Your [v:0] has taken a devastating blow from the [v:1].", "乃[v:0]为[v:1]所重创。");
            AddTranslation("You will not be able to take it with your caravan.", "汝不得携之偕行。");
            AddTranslation("Ah...", "啊……");
            AddTranslation("You won't be seeing your [v:0] again,", "汝不复见乃[v:0]矣，");
            AddTranslation("It has taken too much damage.", "其所受伤已甚。");
            AddTranslation("Ah...", "啊……");
            AddTranslation("Did you permanently kill your [v:0] on purpose?", "汝故永杀乃[v:0]乎？");
            AddTranslation("A shame...", "惜哉……");
            AddTranslation("Ha! There be my first mate!", "哈！我大副来也！");
            AddTranslation("Argh! There be snakes on me ship as well!", "呀！我舟上亦有蛇！");
            AddTranslation("Ha!", "哈！");
            AddTranslation("I should hire ye to get rid of the rest of them!", "我当雇汝尽除此辈！");
            AddTranslation("Ha! It's dead!", "哈！彼死矣！");
            AddTranslation("what?", "何？");
            AddTranslation("Pirates?", "海上之盗？");
            AddTranslation("...", "……");
            AddTranslation("I'll allow it.", "吾许之。");
            AddTranslation("what?", "何？");
            AddTranslation("cheating?", "诈乎？");
            AddTranslation("how dissapointing...", "可惋哉……");
            AddTranslation("...", "……");
            AddTranslation("the game will be soured from a pitifully easy ascent.", "此局将以卑易之胜而索然。");
            AddTranslation("cheater...", "诈者……");
            AddTranslation("Have you no shame?", "汝无耻乎？");
            AddTranslation("To cheat so blatantly...", "乃敢显然为诈……");
            AddTranslation("you should be dead.", "汝本当死。");
            AddTranslation("and yet...", "然而……");
            AddTranslation("how dissapointing...", "可惋哉……");
            AddTranslation("...", "……");
            AddTranslation("I won't tolerate this for much longer...", "我不复容此久矣……");
            AddTranslation("Enough of this.", "止于此。");
            AddTranslation("Yer not dead?", "汝未死乎？");
            AddTranslation("ah...", "啊……");
            AddTranslation("back to normal then?", "则复常乎？");
            AddTranslation("I'll admit, I had gotten used to the changes...", "吾诚言之，我已习于其变矣……");
            AddTranslation("Weak Cards?", "羸牌乎？");
            AddTranslation("This is hard to explain...", "此难言也……");
            AddTranslation("Perhaps they are sick? Yes.", "殆疾乎？然。");
            AddTranslation("A crippling disease afflicted your meager troupe of creatures.", "沉疢加于汝微薄之物众。");
            AddTranslation("Waterborne Cards?", "潜袭牌乎？");
            AddTranslation("This is hard to explain...", "此难言也……");
            AddTranslation("Perhaps a mutation? Yes.", "殆其变乎？然。");
            AddTranslation("Your caravan of creatures had a startling mutation,", "汝所偕行之物众，骤有异变，");
            AddTranslation("They could only survive in the water.", "惟于水中乃能存。");
            AddTranslation("Paralyzed Cards?", "瘫牌乎？");
            AddTranslation("Hmm...", "唔……");
            AddTranslation("Your group of creatures were fatigued from the long journey,", "乃诸物以长途而疲，");
            AddTranslation("but there would be a long way to go yet.", "而前路尚长。");
            AddTranslation("Weak Souled Cards?", "弱魂之牌乎？");
            AddTranslation("Hmm...", "唔……");
            AddTranslation("You will not be able to extract their souls into new creatures,", "汝不得抽其魂以入新物，");
            AddTranslation("For better or worse...", "祸福难知……");
            AddTranslation("The lives of past challengers weighed down on you...", "往昔角者之命数，重压于汝……");
            AddTranslation("Hm?", "唔？");
            AddTranslation("How to explain this...", "斯何以言……");
            AddTranslation("You were running low on supplies that day...", "其日汝资用将匮……");
            AddTranslation("You'll have fewer [c:G][v:0]s[c:] to work with.", "汝所用之[c:G][v:0][c:]将寡。");
            AddTranslation("Hm?", "唔？");
            AddTranslation("An abundance of [c:G][v:0]s[c:]...", "[c:G][v:0][c:]大蕃矣……");
            AddTranslation("Must be mating season...", "殆其交时乎……");
            AddTranslation("Hm?", "唔？");
            AddTranslation("Environmental effects?", "环境之效乎？");
            AddTranslation("how interesting...", "有趣哉……");
            AddTranslation("In order to proceed,", "欲前行，");
            AddTranslation("you had to slog through the wetter parts of the swamp.", "汝不得不跋涉泽中最湿之处。");
            AddTranslation("The thick[c:G][c:G]mud[c:] stuck to your boots, and hindered your movements...", "稠[c:G]泥[c:]著于靴，而缓乃步……");
            AddTranslation("The frigid air was not the only obstacle in your way,", "砭骨之寒，非汝独一之阻也，");
            AddTranslation("the harsh ice and unforgiving snow also stood in your path.", "严冰与积雪亦并横于前。");
            AddTranslation("before long you found yourself in...", "未几，汝已置身于……");
            AddTranslation("a [c:B]hailstorm.[c:]", "一场[c:B]雹暴[c:]。");
            AddTranslation("You found yourself cornered against a sheer rock wall,", "汝迫于峭壁之前，");
            AddTranslation("the [c:G]cliffside.[c:]", "一面[c:G]绝崖[c:]。");
            AddTranslation("Against the cold stone, there would be less space to fight.", "负冷石而战，其地益狭。");
            AddTranslation("The mycologists had left one of their experiments behind,", "蕈家遗其一试物，");
            AddTranslation("unbeknownst to them, it began to fester and grow.", "而彼不知其已溃而长。");
            AddTranslation("even the creatures fighting you would not be safe from the [c:G]fungal mass.[c:]", "虽与汝战之物，亦难免于[c:G]蕈团[c:]之侵。");
            AddTranslation("You stumbled across one of the Prospector's Camps.", "汝偶至采夫一营。");
            AddTranslation("The camp was filled with prospecting tools.", "营中充采具。");
            AddTranslation("pickaxes, headlamps...", "镐、矿灯……");
            AddTranslation("and [c:bR]dynamite.[c:]", "与[c:bR]炸药[c:]。");
            AddTranslation("You came across one of the Angler's Ponds.", "汝过渔父之池一所，");
            AddTranslation("the area stank of rotting fish", "其地满腐鱼之恶臭");
            AddTranslation("emanating from the nearby abandoned buckets of [c:dB]bait.[c:]", "其气出于近侧弃置之[c:dB]饵[c:]桶。");
            AddTranslation("You came across one of the Trapper's Hunting Grounds.", "汝至猎夫之猎场一所。");
            AddTranslation("the stench of blood hung in the air...", "血腥之气悬于空中……");
            AddTranslation("you noticed the numerous [c:G]traps[c:] lying in wait.", "汝见地上多[c:G]阱[c:]伏焉。");
            AddTranslation("You came upon a strange [c:bR]totem.[c:]", "汝遇一怪[c:bR]图腾[c:]。");
            AddTranslation("a mysterious energy swirled around it,", "神异之气旋于其旁，");
            AddTranslation("the creatures nearby seem more agressive than usual...", "近侧诸物似较常时益暴……");
            AddTranslation("Ah...", "啊……");
            AddTranslation("a [c:bR]Blood Moon.[c:]", "一轮[c:bR]血月[c:]。");
            AddTranslation("Er...", "呃……");
            AddTranslation("You...", "汝……");
            AddTranslation("...", "……");
            AddTranslation("...What?", "……何？");
            AddTranslation("I am at a loss for words.", "我无以言。");
            AddTranslation("The wind was howling around you.", "狂风号于汝四周。");
            AddTranslation("Stuck in the middle of a blizzard,", "困于暴雪之中，");
            AddTranslation("You heard rumbling from the mountains above.", "汝闻上方群山有殷殷之声。");
            AddTranslation("Here it comes...", "其来也……");
            AddTranslation("an [c:B]avalanche.[c:]", "一场[c:B]雪崩[c:]。");
            AddTranslation("You stumble across a strange black stone.", "汝偶见一怪黑石。");
            AddTranslation("A stone tablet sits in front of it, clearly made for sacrifices.", "其前有石坛，显为牲祀而设。");
            AddTranslation("Perhaps a certain creature may cause a reaction?", "或某物能致其应乎？");
            AddTranslation("The obelisk trembles in delight.", "方尖碑喜而震。");
            AddTranslation("A goat is truly a worthy sacrifice.", "山羊诚堪祀也。");
            AddTranslation("You won't be seeing it again.", "汝不复见之矣。");
            AddTranslation("The obelisk rumbles with anger.", "方尖碑忿而震。");
            AddTranslation("A pelt is a truly pitiful sacrifice.", "革诚鄙祭也。");
            AddTranslation("...", "……");
            AddTranslation("...That is not a proper sacrifice.", "……此非正祭。");
            AddTranslation("Stop this.", "止。");
            AddTranslation("You...", "汝……");
            AddTranslation("This is bloodshed without meaning.", "此徒流血耳。");
            AddTranslation("[v:0]...", "[v:0]……");
            AddTranslation("Hmm?", "唔？");
            AddTranslation("What is this?", "此何物也？");
            AddTranslation("Heh heh heh...", "呵呵呵……");
            AddTranslation("Ye walked into th' pirate's cove!", "汝误入海上之盗之巢矣！");
            AddTranslation("Me crew will get rid of ye quick!", "吾徒众须臾除汝！");
            AddTranslation("You carve through the thick underbrush and foilage.", "汝披荆斩棘而行。");
            AddTranslation("The trees blotting out the sun...", "木阴蔽日……");
            AddTranslation("As you travel, you hear the woods start to creak around you.", "行旅之间，汝闻林木四周始作格格之声。");
            AddTranslation("You should know better than to walk in the darkness...", "汝当知不宜行于冥暗……");
            AddTranslation("As your caravan of creatures travels, you hear a rushing sound.", "汝所偕行之物众行时，闻有急流之声。");
            AddTranslation("You climb to a higher place as water flows around you.", "汝登高处，而水四面奔流。");
            AddTranslation("You are caught in a [c:B]flood.[c:]", "汝困于[c:B]洪水[c:]。");
            AddTranslation("Only the terrain and flying creatures will be able to avoid the waters.", "惟地形牌与翔物得免于水。");
            AddTranslation("As your caravan of creatures moves across a clearing, the winds blow stronger.", "汝所偕行之物众过一旷地，而风益劲。");
            AddTranslation("A strong breeze greets your face, and you grasp onto the surroundings for dear life.", "劲风迎面而至，汝攀援四旁以自全。");
            AddTranslation("Your creatures are blown [c:G]airborne.[c:]", "乃诸物皆为风吹而[c:G]翔袭[c:]。");
            AddTranslation("Only burrowing and submerged creatures will be able to avoid the gusts.", "惟潜地与潜水之物得避此风。");
            AddTranslation("The Breeze blows...", "微风作矣……");
            AddTranslation("You come across a pile of corpses.", "汝见积尸一堆。");
            AddTranslation("A strange energy swirls around them as you approach.", "汝既近，则怪气旋其旁。");
            AddTranslation("Then...", "俄而……");
            AddTranslation("[c:R]The dead walk.[c:]", "[c:R]亡者起行。[c:]");
            AddTranslation("[c:R]The dead walk.[c:]", "[c:R]亡者起行。[c:]");
            AddTranslation("You came across an overgrown glade.", "汝过一蔓生之隙地。");
            AddTranslation("The trees seemed taller, and stronger than usual.", "木似较常时益高且壮。");
            AddTranslation("Your creatures grew faster as well.", "乃诸物亦长益速。");
            AddTranslation("<color=#25C102>Flash Growth.</color>", "<color=#25C102>急长。</color>");
            AddTranslation("<color=#25C102>Flash Growth.</color>", "<color=#25C102>急长。</color>");
            AddTranslation("Hm?", "唔？");
            AddTranslation("You're decreasing the number of vessels you have?", "汝减所蓄之皿数乎？");
            AddTranslation("Surely a player as bad as you needs the extra chump blockers?", "如汝之拙者，岂不需此徒御者乎？");
            AddTranslation("You'll see.", "后自知之。");
            AddTranslation("Hm?", "唔？");
            AddTranslation("You're increasing the number of vessels you have?", "汝益所蓄之皿数乎？");
            AddTranslation("Makes sense.", "然。");
            AddTranslation("After all, a player as bad as you needs the extra chump blockers.", "毕竟如汝之拙者，需此徒御者。");
            AddTranslation("[v:0] vessels...", "[v:0]皿……");
            AddTranslation("Oh?", "噫？");
            AddTranslation("You couldn't even stick to the changes?", "汝连此变亦守不能乎？");
            AddTranslation("Pathetic.", "鄙矣。");
            AddTranslation("Oh?", "噫？");
            AddTranslation("My own Ourobot?", "我之机衔尾蛇乎？");
        }
    }
}
